In [1]:
from itertools import product
import io
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
import pandas as pd
import requests
from requests.adapters import HTTPAdapter
from urllib3.util import Retry

In [2]:
def build_dhis2_metadata_map(session: requests.Session, base_url: str) -> dict[str, str]:
    meta_map = {}
    endpoints = {
        "trackedEntityAttributes": f"{base_url}/api/trackedEntityAttributes.json?fields=id,displayName&paging=false",
        "dataElements": f"{base_url}/api/dataElements.json?fields=id,displayName&paging=false",
        "programStages": f"{base_url}/api/programStages.json?fields=id,displayName&paging=false",
        "programs": f"{base_url}/api/programs.json?fields=id,displayName&paging=false",
        "organisationUnits": f"{base_url}/api/organisationUnits.json?fields=id,displayName&paging=false",
    }
    for resource, url in endpoints.items():
        try:
            res = session.get(url, timeout=30)
            if res.ok:
                items = res.json().get(resource, [])
                for item in items:
                    meta_map[item["id"]] = item.get("displayName", item["id"])
        except Exception:
            pass
    return meta_map

def get_data_dhis2(web: str, username: str, password: str, idprogram: list[str], idou: list[str]) -> pd.DataFrame:
    base_url = web.rsplit("/api/", 1)[0].rstrip("/")
    endpoint = f"{base_url}/api/trackedEntityInstances.json"

    session = requests.Session()
    session.auth = (username, password)
    session.headers.update({"Accept": "application/json", "User-Agent": "DHIS2-Python-Script/1.0"})

    retries = Retry(total=5, backoff_factor=2, status_forcelist=[500, 502, 503, 504])
    adapter = HTTPAdapter(max_retries=retries)
    session.mount("https://", adapter)
    session.mount("http://", adapter)

    meta_map = build_dhis2_metadata_map(session, base_url)
    all_records = []

    for prog, ou in product(idprogram, idou):
        page = 1
        page_size = 100

        while True:
            params = {
                "program": prog,
                "ou": ou,
                "ouMode": "DESCENDANTS",
                "pageSize": page_size,
                "page": page,
                "totalPages": "true",
                "fields": "trackedEntityInstance,orgUnit,created,lastUpdated,attributes[attribute,displayName,value],enrollments[enrollment,program,orgUnit,enrolledAt,occurredAt,status,events[event,programStage,occurredAt,status,dataValues[dataElement,value]]]",
            }
            try:
                response = session.get(endpoint, params=params, timeout=45)
                if not response.ok:
                    break

                data = response.json()
                instances = data.get("trackedEntityInstances", [])
                if not instances:
                    break

                for instance in instances:
                    ou_id = instance.get("orgUnit")
                    ou_name = meta_map.get(ou_id, ou_id)
                    prog_name = meta_map.get(prog, prog)

                    row = {
                        "program_id": prog,
                        "program_name": prog_name,
                        "trackedEntityInstance": instance.get("trackedEntityInstance"),
                        "orgUnit_id": ou_id,
                        "Org Unit Name": ou_name,
                        "created": instance.get("created"),
                        "lastUpdated": instance.get("lastUpdated"),
                    }

                    for attr in instance.get("attributes", []):
                        attr_id = attr.get("attribute")
                        col_name = attr.get("displayName") or meta_map.get(attr_id) or attr_id
                        row[col_name] = attr.get("value")

                    for enrollment in instance.get("enrollments", []):
                        if enrollment.get("program") == prog:
                            row["enrollment_date"] = enrollment.get("enrolledAt")
                            row["enrollment_status"] = enrollment.get("status")

                            for event in enrollment.get("events", []):
                                stage_id = event.get("programStage")
                                stage_name = meta_map.get(stage_id, f"Stage_{stage_id}")

                                for dv in event.get("dataValues", []):
                                    de_id = dv.get("dataElement")
                                    de_name = meta_map.get(de_id, f"Element_{de_id}")
                                    col_key = f"[{stage_name}] {de_name}"
                                    row[col_key] = dv.get("value")

                    all_records.append(row)

                pager = data.get("pager", {})
                if page >= pager.get("pageCount", 1):
                    break
                page += 1
            except Exception:
                break

    session.close()
    return pd.DataFrame(all_records)

def convert_df_to_excel_bytes(df: pd.DataFrame) -> bytes:
    output = io.BytesIO()
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
    data_font = Font(name="Segoe UI", size=10)
    alt_fill = PatternFill(start_color="F2F5F9", end_color="F2F5F9", fill_type="solid")
    thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

    group_col = "program_name" if "program_name" in df.columns else "program_id"
    for prog_label, prog_df in df.groupby(group_col, dropna=False):
        sheet_title = str(prog_label)[:30] if pd.notna(prog_label) else "Unknown_Program"
        ws = wb.create_sheet(title=sheet_title)
        ws.views.sheetView[0].showGridLines = True

        prog_df_clean = prog_df.dropna(how="all", axis=1)
        headers = list(prog_df_clean.columns)
        ws.append(headers)

        for col_idx in range(1, len(headers) + 1):
            cell = ws.cell(row=1, column=col_idx)
            cell.fill, cell.font = header_fill, header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

        for row_idx, record in enumerate(prog_df_clean.to_dict(orient="records"), start=2):
            ws.append([record.get(col, "") for col in headers])
            is_even = row_idx % 2 == 0
            for col_idx in range(1, len(headers) + 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                cell.font, cell.border = data_font, thin_border
                cell.alignment = Alignment(vertical="center")
                if is_even: cell.fill = alt_fill

        ws.freeze_panes = "A2"
        for col in ws.columns:
            max_len = max(len(str(cell.value or "")) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = min(max(max_len + 4, 12), 45)

    wb.save(output)
    return output.getvalue()


# Define Mappings
PROGRAM_MAP = {
    "Registration & Screening": "UZF0HrTlps0",
    "Diagnostic Evaluation": "GvywHD6crky",
    "TB Case Surveillance": "Lt6P15ps7f6",
    "TB Contact Investigation TPT": "cQsXTtAJ3HW"
}

TOWNSHIP_OU_MAP = {
    "HLG (Hlaing)": ["KqjORlUe8Yc"],
    "KMD (Kyeemyindaing)": ["rTTCKrLpxTB"],
    "SDG (Dagon Myothit South)": ["XHz6CPxTAbR"],
    "TGG (Thingangyun)": ["aBfPB9AwbF5"],
    "SOK (South Okkalapa)": ["OeZsFpNKLP5"],
    "MYG (Mayangone)": ["mPwLv1cjror"],
    "SPT (Shwepyithar)": ["aMAEOgli6W8"]
}

In [3]:
prog_ids = list(PROGRAM_MAP.values())
prog_ids

['UZF0HrTlps0', 'GvywHD6crky', 'Lt6P15ps7f6', 'cQsXTtAJ3HW']

In [4]:
ou_ids = [id for ids in TOWNSHIP_OU_MAP.values() for id in ids]
ou_ids

['KqjORlUe8Yc',
 'rTTCKrLpxTB',
 'XHz6CPxTAbR',
 'aBfPB9AwbF5',
 'OeZsFpNKLP5',
 'mPwLv1cjror',
 'aMAEOgli6W8']

In [5]:
web_url = "https://hmistraining.mm.dhis2.net/train"
username = "Ygn_NTP1"
password = "District@1"

In [6]:
df_result = get_data_dhis2(web_url, username, password, prog_ids, ou_ids)

In [7]:
df_result

,program_id,program_name,trackedEntityInstance,orgUnit_id,Org Unit Name,created,lastUpdated,Nationality,Home Address,GEN - Name,...,[Screening & Testing] TB-HH - Active TB testing,[Screening & Testing] CXR screening date,[Screening & Testing] Enroll to Diagnostic Evaluation,[Screening & Testing] TB CS - Risk factor smoking,[Screening & Testing] TB CS - Risk factor diabetes,[Screening & Testing] Referral organization,[Screening & Testing] Referral activity,[Screening & Testing] CXR screening done,[Screening & Testing] TB CS - HIV infection,[Screening & Testing] Previous TB History
0,UZF0HrTlps0,Registration and Screening,h29C0X4VZ6v,KqjORlUe8Yc,12. YTP/MATA (Hlaing),2026-06-02T05:13:41.473,2026-06-04T05:17:31.859,National,"46, Thayat Myaing St",Thein Htay Aung,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UZF0HrTlps0,Registration and Screening,zySTcqaFVh8,KqjORlUe8Yc,12. YTP/MATA (Hlaing),2026-06-02T05:23:33.088,2026-06-04T05:17:54.397,National,"99, Pazuntaung 3st,",Min Min Tun,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UZF0HrTlps0,Registration and Screening,ZFerVs0glZL,KqjORlUe8Yc,12. YTP/MATA (Hlaing),2026-06-02T05:26:21.864,2026-06-04T05:18:59.291,National,"Zayyamingalar 2st,\n",Ha Li Mar B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UZF0HrTlps0,Registration and Screening,pT1gXZAmImn,KqjORlUe8Yc,12. YTP/MATA (Hlaing),2026-06-02T05:28:51.847,2026-06-04T05:19:44.128,National,"No.142, ThuKhaMyaing 2st,",Kyaw Soe Min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UZF0HrTlps0,Registration and Screening,UyxHvIrEdsG,KqjORlUe8Yc,12. YTP/MATA (Hlaing),2026-06-02T05:32:22.607,2026-06-04T05:20:24.091,National,"No.162, Aung Chan Thar St,",Phyu Phyu Win,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,Lt6P15ps7f6,TB Case Surveillance,xYpfsEjE5B2,AQpmqMcXgPN,12. MATA (Dagon Myothit (South)),2026-09-12T07:41:15.289,2026-09-12T07:47:59.801,National,NaN,lone lay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,Lt6P15ps7f6,TB Case Surveillance,rsrnxQ0iFeA,rTTCKrLpxTB,12. YTP/MATA (Kyeemyindaing),2026-09-15T07:33:47.161,2026-09-15T07:40:20.787,National,NaN,TEST_TPS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422,Lt6P15ps7f6,TB Case Surveillance,ueaJQJ3ZMYq,OeZsFpNKLP5,12. YTP/MMA (South Okkalapa),2026-08-15T07:17:03.011,2026-08-15T09:40:36.754,National,Lanmadaw\n304,Thet Ko,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
423,Lt6P15ps7f6,TB Case Surveillance,MeHZdcgLuZw,mPwLv1cjror,12. YTP/MMA (Mayangone),2026-08-16T03:04:55.731,2026-08-16T04:08:05.801,National,NaN,Mingalar,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,cQsXTtAJ3HW,TB Household Contact Investigation,iY92KxJrh5V,KqjORlUe8Yc,12. YTP/MATA (Hlaing),2026-09-23T07:56:06.963,2026-09-23T08:01:51.827,National,"No. 843, Muditar Housing, 2 Ward, Baho Road, M...",Thet Ko Ko,...,true,2026-09-23,true,Never,NEGATIVE,ARC,CBTBC,true,UNKNOWN,NO

In [9]:
print(df_result.columns.to_list())

['program_id', 'program_name', 'trackedEntityInstance', 'orgUnit_id', 'Org Unit Name', 'created', 'lastUpdated', 'Nationality', 'Home Address', 'GEN - Name', 'Father Name', 'District', 'GEN - Date of birth', 'Age', 'Ward', 'Unique ID (UPI)', 'GEN - Sex', 'Ward / Village tract', 'NRC No.', 'GEN - Contact phone number (local)', 'Township (T)', 'Region/State', 'enrollment_date', 'enrollment_status', '[TB Screening] Loss of appetite', '[TB Screening] TB CS - Risk factor alcohol', '[TB Screening] CXR result category', '[TB Screening] TB CS - Risk factor undernourishment', '[TB Screening] Cough more than 2 weeks', '[TB Screening] Chest pain', '[TB Screening] CXR screening date', '[TB Screening] TB CS - Risk factor smoking', '[TB Screening] TB CS - Risk factor diabetes', '[TB Screening] CXR screening facility type', '[TB Screening] Referral organization', '[TB Screening] Referral activity', '[TB Screening] Type of CXR', '[TB Screening] CXR screening done', '[TB Screening] CXR result', '[TB Screening] TB CS - HIV infection', '[TB Screening] Fatigue and Tiredness', '[TB Screening] Previous TB History', '[TB Screening] Age (at screening)', '[TB Screening] No symptoms related with TB', 'Passport number', 'Village', 'Country of origin', '[TB Screening] Night sweats', '[TB Screening] Enroll to Diagnostic Evaluation', '[TB Screening] Weight loss', '[TB Screening] Number of previous TB episodes', '[TB Screening] Year of last TB Treatment', '[TB Screening] TB CS - Registration - Type of patient in last TB Treatment', '[TB Screening] Previous TB regimen', 'GEN - Date of birth is estimated', '[TB Screening] Any TB drug resistance history?', '[TB Screening] Household Contact', '[TB Screening] Other referral organisation (Specify)', '[TB Screening] Haemoptysis', '[TB Screening] Fever more than 2 weeks', '[TB Screening] Other symptoms related with TB', '[TB Screening] Specify other symptoms', '[TB Screening] Current activity', '[TB Screening] Weight (in kgs)', '[TB Screening] BMI', '[TB Screening] Height (in inches)', '[TB Screening] Healthcare worker population', '[TB Screening] TB CS - HIV status date', '[TB Screening] Breathlessness', '[TB Screening] Migrant population', '[01. Screening and Case History] TB CS - Risk factor alcohol', '[01. Screening and Case History] CXR result category', '[01. Screening and Case History] TB CS - Risk factor undernourishment', '[01. Screening and Case History] CXR screening date', '[01. Screening and Case History] TB CS - Risk factor smoking', '[01. Screening and Case History] TB CS - Risk factor diabetes', '[01. Screening and Case History] CXR screening facility type', '[01. Screening and Case History] Referral organization', '[01. Screening and Case History] Referral activity', '[01. Screening and Case History] Type of CXR', '[01. Screening and Case History] CXR screening done', '[01. Screening and Case History] CXR result', '[01. Screening and Case History] TB CS - HIV infection', '[01. Screening and Case History] No symptoms related with TB', '[01. Screening and Case History] Previous TB History', '[01. Screening and Case History] Age (at screening)', 'Tracker Id', 'Unique ID (UPI) - Index Case', 'Relationship with index', '[01. Screening and Case History] Cough more than 2 weeks', '[01. Screening and Case History] Chest pain', '[01. Screening and Case History] Loss of appetite', '[01. Screening and Case History] Weight loss', '[01. Screening and Case History] Fatigue and Tiredness', '[01. Screening and Case History] Haemoptysis', '[01. Screening and Case History] Night sweats', '[01. Screening and Case History] Number of previous TB episodes', '[01. Screening and Case History] Year of last TB Treatment', '[01. Screening and Case History] Any TB drug resistance history?', '[01. Screening and Case History] TB CS - Registration - Type of patient in last TB Treatment', '[01. Screening and Case History] Previous TB regimen', '[01. Screening and Case History] Household Contact', '[01. Screening and Case History] Fever more than 2 weeks', '[01. Screening and Case History] Current activity', '[01. Screening and Case History] TB CS - HIV status date', '[01. Screening and Case History] Weight (in kgs)', '[01. Screening and Case History] BMI', '[01. Screening and Case History] Height (in inches)', '[02. Examination Request and Results] Result dispatch date', '[02. Examination Request and Results] Result date', '[02. Examination Request and Results] TB-LAB - Xpert MTB/RIF Ultra', '[02. Examination Request and Results] TB CS - Resistance classification', '[02. Examination Request and Results] Result data available for dispatch', '[03. TB Diagnosis] TB CS Diagnosis', '[03. TB Diagnosis] Enroll to TB Case Surveillance Program', '[03. TB Diagnosis] TB CS - Site of disease', '[03. TB Diagnosis] Type of TB patient', '[03. TB Diagnosis] TB CS - Resistance classification', '[03. TB Diagnosis] TB CS - Diagnosis date', '[03. TB Diagnosis] TB CS - Confirmation method', '[03. TB Diagnosis] TB CS - Diagnostic note', '[01. Screening and Case History] Other symptoms related with TB', '[01. Screening and Case History] Healthcare worker population', '[02. Examination Request and Results] Reject sample', '[02. Examination Request and Results] Specimen type', '[02. Examination Request and Results] TB-LAB - Xpert MTB/RIF Ultra result', '[02. Examination Request and Results] Date of specimen collected', '[02. Examination Request and Results] Visual appearance', '[01. Screening and Case History] Breathlessness', '[02. Examination Request and Results] Xpert MTB/XDR Result for Km', '[02. Examination Request and Results] Date of Sample Received at Laboratory', '[02. Examination Request and Results] Xpert MTB/XDR Result for Eto', '[02. Examination Request and Results] Xpert MTB/XDR', '[02. Examination Request and Results] Xpert MTB/XDR Result for Am', '[02. Examination Request and Results] Xpert MTB/XDR (Examination)', '[02. Examination Request and Results] Xpert MTB/XDR Result for Cm', '[02. Examination Request and Results] Xpert MTB/XDR Result for Fq', '[02. Examination Request and Results] Reason for Xpert MTB/XDR request', '[02. Examination Request and Results] Xpert MTB/XDR Result for INH', '[02. Examination Request and Results] Samples received (number)', '[02. Examination Request and Results] Name of laboratory examination facility', '[01. Screening and Case History] Migrant population', '[02. Examination Request and Results] TB-LAB - Sample ID', '[03. TB Diagnosis] TB CS - Manually assigned resistance classification', '[03. TB Diagnosis] TB CS - Reassign resistance classification', '[01. Screening and Case History] Activity Notes', '[1. Screening, Diagnosis and Notification] Number of previous TB episodes', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor alcohol', '[1. Screening, Diagnosis and Notification] Fever more than 2 weeks', '[1. Screening, Diagnosis and Notification] Night sweats', '[1. Screening, Diagnosis and Notification] Height (in inches)', '[1. Screening, Diagnosis and Notification] TB CS - Site of disease', '[1. Screening, Diagnosis and Notification] Year of last TB Treatment', '[1. Screening, Diagnosis and Notification] Type of TB patient', '[1. Screening, Diagnosis and Notification] Other symptoms related with TB', '[1. Screening, Diagnosis and Notification] TB CS - ART patient ID', '[1. Screening, Diagnosis and Notification] CXR screening facility type', '[1. Screening, Diagnosis and Notification] Type of CXR', '[1. Screening, Diagnosis and Notification] CXR screening done', '[1. Screening, Diagnosis and Notification] TB CS - HIV status date', '[1. Screening, Diagnosis and Notification] Current activity', '[1. Screening, Diagnosis and Notification] TB CS - Resistance classification', '[1. Screening, Diagnosis and Notification] Any TB drug resistance history?', '[1. Screening, Diagnosis and Notification] Weight (in kgs)', '[1. Screening, Diagnosis and Notification] BMI', '[1. Screening, Diagnosis and Notification] CXR result category', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor undernourishment', '[1. Screening, Diagnosis and Notification] TB CS - Registration - Type of patient in last TB Treatment', '[1. Screening, Diagnosis and Notification] TB CS - Confirmation method', '[1. Screening, Diagnosis and Notification] CXR screening date', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor smoking', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor diabetes', '[1. Screening, Diagnosis and Notification] Referral organization', '[1. Screening, Diagnosis and Notification] Referral activity', '[1. Screening, Diagnosis and Notification] CXR result', '[1. Screening, Diagnosis and Notification] TB CS - HIV infection', '[1. Screening, Diagnosis and Notification] Previous TB regimen', '[1. Screening, Diagnosis and Notification] TB CS - Diagnosis date', '[1. Screening, Diagnosis and Notification] Fatigue and Tiredness', '[1. Screening, Diagnosis and Notification] Previous TB History', '[1. Screening, Diagnosis and Notification] Age (at screening)', '[2. TB Treatment] TB CS - Resistance at diagnosis', '[2. TB Treatment] TB CS - First-line treatment regimen composition', '[2. TB Treatment] TB CS - Treatment initiation delay (days)', '[2. TB Treatment] TB CS - First-line treatment start date', '[2. TB Treatment] TB CS - Outcome due date', '[2. TB Treatment] TB CS - Resistance classification', '[2. TB Treatment] TB CS - Diagnosis date', '[2. TB Treatment] TB CS - Treatment regimen', '[1. Screening, Diagnosis and Notification] Cough more than 2 weeks', '[1. Screening, Diagnosis and Notification] TB CS - Diagnostic note', '[1. Screening, Diagnosis and Notification] Haemoptysis', '[1. Screening, Diagnosis and Notification] Breathlessness', '[1. Screening, Diagnosis and Notification] Weight loss', '[1. Screening, Diagnosis and Notification] Loss of appetite', '[2. TB Treatment] TB CS - Manually assigned resistance classification', '[2. TB Treatment] TB CS - Reassign resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Reassign resistance classification', '[1. Screening, Diagnosis and Notification] Migrant population', '[1. Screening, Diagnosis and Notification] TB CS - Manually assigned resistance classification', '[1. Screening, Diagnosis and Notification] Healthcare worker population', '[1. Screening, Diagnosis and Notification] TB CS - Notification date', '[1. Screening, Diagnosis and Notification] TB CS - Case notification', '[1. Screening, Diagnosis and Notification] Started on Treatment', '[4. Outcome] TB CS - Treatment outcome delay (weeks)', '[4. Outcome] TB CS - Treatment outcome', '[Screening & Testing] Weight (in kgs)', '[Screening & Testing] BMI', '[Screening & Testing] TB CS - Risk factor alcohol', '[Screening & Testing] CXR result category', '[Screening & Testing] TB CS - Risk factor undernourishment', '[Screening & Testing] Height (in inches)', '[Screening & Testing] TB-HH - Active TB test result', '[Screening & Testing] TB-HH - Screening', '[Screening & Testing] TB-HH - Active TB testing', '[Screening & Testing] CXR screening date', '[Screening & Testing] Enroll to Diagnostic Evaluation', '[Screening & Testing] TB CS - Risk factor smoking', '[Screening & Testing] TB CS - Risk factor diabetes', '[Screening & Testing] Referral organization', '[Screening & Testing] Referral activity', '[Screening & Testing] CXR screening done', '[Screening & Testing] TB CS - HIV infection', '[Screening & Testing] Previous TB History']

In [10]:
def convert_df_to_excel_bytes(df: pd.DataFrame) -> bytes:
    output = io.BytesIO()
    wb = openpyxl.Workbook()
    wb.remove(wb.active)  # Remove default active sheet

    # Define Column Selection for YgnTBPro
    SelectedColumnList = [
        'Org Unit Name', 'created', 'lastUpdated', 'Nationality', 'Home Address', 
        'GEN - Name', 'Father Name', 'District', 'GEN - Date of birth', 'Age', 
        'Ward', 'Unique ID (UPI)', 'GEN - Sex', 'Ward / Village tract', 'NRC No.', 
        'GEN - Contact phone number (local)', 'Township (T)', 'Region/State', 
        'enrollment_date', 'enrollment_status', '[TB Screening] Loss of appetite', 
        '[TB Screening] TB CS - Risk factor alcohol', '[TB Screening] CXR result category', 
        '[TB Screening] TB CS - Risk factor undernourishment', '[TB Screening] Cough more than 2 weeks', 
        '[TB Screening] Chest pain', '[TB Screening] CXR screening date', 
        '[TB Screening] TB CS - Risk factor smoking', '[TB Screening] TB CS - Risk factor diabetes', 
        '[TB Screening] CXR screening facility type', '[TB Screening] Referral organization', 
        '[TB Screening] Referral activity'
    ]

    # Style Definitions
    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
    data_font = Font(name="Segoe UI", size=10)
    alt_fill = PatternFill(start_color="F2F5F9", end_color="F2F5F9", fill_type="solid")
    thin_border = Border(
        left=Side(style="thin", color="D9D9D9"),
        right=Side(style="thin", color="D9D9D9"),
        top=Side(style="thin", color="D9D9D9"),
        bottom=Side(style="thin", color="D9D9D9")
    )

    def _format_and_populate_sheet(ws, sheet_df: pd.DataFrame):
        """Helper function to format headers, cells, zebra-striping, and auto-fit columns."""
        ws.views.sheetView[0].showGridLines = True
        
        # Clean up columns that are completely empty
        clean_df = sheet_df.dropna(how="all", axis=1)
        headers = list(clean_df.columns)
        
        if not headers:
            return

        # Append Header
        ws.append(headers)
        for col_idx in range(1, len(headers) + 1):
            cell = ws.cell(row=1, column=col_idx)
            cell.fill, cell.font = header_fill, header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

        # Append Data Rows & Apply Styling
        for row_idx, record in enumerate(clean_df.to_dict(orient="records"), start=2):
            ws.append([record.get(col, "") for col in headers])
            is_even = row_idx % 2 == 0
            for col_idx in range(1, len(headers) + 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                cell.font, cell.border = data_font, thin_border
                cell.alignment = Alignment(vertical="center")
                if is_even:
                    cell.fill = alt_fill

        # Freeze Headers & Set Column Widths
        ws.freeze_panes = "A2"
        for col in ws.columns:
            max_len = max(len(str(cell.value or "")) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = min(max(max_len + 4, 12), 45)

    # 1. ADD CONSOLIDATED SHEET (All Data)
    ws_consolidated = wb.create_sheet(title="Consolidated")
    _format_and_populate_sheet(ws_consolidated, df)

    # 2. ADD YgnTBPro SHEET (Filter Selected Columns that exist in df)
    existing_cols = [col for col in SelectedColumnList if col in df.columns]
    df_ygntbpro = df[existing_cols] if existing_cols else pd.DataFrame()
    ws_ygntbpro = wb.create_sheet(title="YgnTBPro")
    _format_and_populate_sheet(ws_ygntbpro, df_ygntbpro)

    # 3. ADD PROGRAM-SPECIFIC SHEETS
    group_col = "program_name" if "program_name" in df.columns else "program_id"
    if group_col in df.columns:
        for prog_label, prog_df in df.groupby(group_col, dropna=False):
            # Clean sheet title (Max 30 chars, remove illegal characters)
            sheet_title = str(prog_label)[:30] if pd.notna(prog_label) else "Unknown_Program"
            for char in [":", "\\", "/", "?", "*", "[", "]"]:
                sheet_title = sheet_title.replace(char, "_")
            
            ws_prog = wb.create_sheet(title=sheet_title)
            _format_and_populate_sheet(ws_prog, prog_df)

    wb.save(output)
    return output.getvalue()

In [11]:
convert_df_to_excel_bytes(df_result)

b'PK\x03\x04\x14\x00\x00\x00\x08\x00E~8]F\xc7MH\x95\x00\x00\x00\xcd\x00\x00\x00\x10\x00\x00\x00docProps/app.xmlM\xcfM\x0b\xc20\x0c\x06\xe0\xbfRv\xb7\x99\x8a\x1e\xa4\x0eD=\x8a\x9e\xbc\xcf.u\x85\xb6)m\x84\xfa\xef\xed\x04?nyy\xc8\x1b\xa2.\x89"&\xb6\x98E\xf1.\xe4m32\xc7\r@\xd6#\xfa>\xcb\xca\xa1\x8a\xa1\xe4{\xae1\xdd\x81\x8c\xb1\x1a\x0f\xa4\x1f\x1e\x03\xc3\xa2m\xd7\x80\x851\x0c8\xcc\xe2\xb7\xb0\xe9\xd4.Fgu\xcf\x96Bw\xb2:Q&\xc3\xe2X4:\xb1\'\x1f\xab\xdc\x1c\n\x10\xe7z%>\x8b\x13K9\x97+\x05\xff\x8bS\xcb\x15S\x9e\xe6\xcao\xfcd\x05\xbf\x07\xba\x17PK\x03\x04\x14\x00\x00\x00\x08\x00E~8],\x19\xa4\xa2\xee\x00\x00\x00\xcb\x01\x00\x00\x11\x00\x00\x00docProps/core.xml\x95\x91\xc1N\xc30\x0c\x86_e\xca\xbdu\x9a\xa1\x89E]. N !1\t\xc4-J\xbc-\xa2i\xa3\xc4\xa8\xdd\xdb\x93\x96\xad\x1b\x82\x0b\xc7\xf8\xff\xfc\xd9Vj\x13\xa4\xe9">\xc7.`$\x87i1\xf8\xa6M\xd2\x84\r;\x10\x05\t\x90\xcc\x01\xbdNe&\xda\x1c\xee\xba\xe85\xe5g\xdcC\xd0\xe6C\xef\x11\x04\xe7+\xf0H\xdaj\xd20\n\x8b0\x1b\xd9Ii\xcd\xac\x0c\x9f\xb1\x99\x04\xd6\x006\xe8\xb1\xa5\x04UY\xc1\x85%\x8c>\xfd\xd90%39$7S}\xdf\x97\xfdr\xe2\xf2F\x15\xbc==\xbeL\xcb\x17\xaeM\xa4[\x83L\xd5\xd6H\x13QS\x17\xd5xQ8\x0eM\rW\xc5\xfa4\xfb\xbb\x80v\x91\'H:\x06\xdc\xb0s\xf2\xba\xbc\xbb\xdf>0%\xb8X\x15|]\x88\x9b-_K\xc1%\xbf}\x1f]?\xfa/B\xdfY\xb7s\xff3V\xd5\x95\xf1,P5\xfc\xfa7\xf5\x05PK\x03\x04\x14\x00\x00\x00\x08\x00E~8]\x99\\\x9c#\x10\x06\x00\x00\x9c\'\x00\x00\x13\x00\x00\x00xl/theme/theme1.xml\xedZ[s\xda8\x14~\xef\xaf\xd0xg\xf6m\x0b\xc66\x81\xb6\xb4\x13siv\xdb\xb4\x99\x84\xedN\x1f\x85\x11X\x8dlyd\x91\x84\x7f\xbfG6\x10\xcb\x96\r\xed\x92M\xba\x9b<\x04,\xe9\xfb\xceEG\xe7\xe88y\xf3\xee.b\xe8\x86\x88\x94\xf2x`\xd9/\xdb\xd6\xbb\xb7/\xde\xe0W2$\x11A0\x19\xa7\xaf\xf0\xc0\n\xa5L^\xb5Zi\x00\xc38}\xc9\x13\x12\xc3\xdc\x82\x8b\x08Kx\x14\xcb\xd6\\\xe0[\x1a/#\xd6\xea\xb4\xdb\xddV\x84il\xa1\x18Gd`}^,h@\xd0TQZo_ \xb4\xe5\x1f3\xf8\x15\xcbT\x8de\xa3\x01\x13WA&\xb9\x88\xb4\xf2\xf9l\xc5\xfc\xda\xde>e\xcf\xe9:\x1d2\x81n0\x1bX \x7f\xceo\xa7\xe4NZ\x88\xe1T\xc2\xc4\xc0jg?Vk\xc7\xd1\xd2H\x80\x82\xc9}\x94\x05\xbaI\xf6\xa3\xd3\x15\x082\r;:\x9dX\xcev|\xf6\xc4\xed\x9f\x8c\xca\xdat4m\x1a\xe0\xe3\xf1x8\xb6\xcb\xd2\x8bp\x1c\x04\xe0Q\xbb\x9e\xc2\x9d\xf4l\xbf\xa4A\t\xb4\xa3i\xd0d\xd8\xf6\xda\xae\x91\xa6\xaa\x8dSO\xd3\xf7}\xdf\xeb\x9bh\x9c\n\x8d[O\xd3kw\xdd\xd3\x8e\x89\xc6\xad\xd0x\r\xbe\xf1O\x87\xc3\xae\x89\xc6\xab\xd0t\xebi&\'\xfd\xaek\xa4\xe9\x16hBF\xe3\xebz\x12\x15\xb5\xe5@\xd3 \x00Xpv\xd6\xcc\xd2\x03\x96^)\xfau\x94\x1a\xd9\x1d\xbb\xddA\\\xf0X\xee9\x89\x11\xfe\xc6\xc5\x04\xd6i\xd2\x19\x964Fr\x9d\x90\x05\x0e\x007\xc4\xd1LP|\xafA\xb6\x8a\xe0\xc2\x92\xd2\\\x90\xd6\xcf)\xb5P\x1a\x08\x9a\xc8\x81\xf5G\x82!\xc5\xdc\xaf\xfd\xf5\x97\xbb\xc9\xa43z\x9d}:\xcek\x94\x7fi\xab\x01\xa7\xed\xbb\x9b\xcf\x93\xfcs\xe8\xe4\x9f\xa7\x93\xd7MB\xcep\xbc,\t\xf1\xfb#[a\x87\'n;\x13r:\x1cgB|\xcf\xf6\xf6\x91\xa5%2\xcf\xef\xf9\n\xebN<g\x1fV\x96\xb0]\xcf\xcf\xe4\x9e\x8cr#\xbb\xdd\xf6X}\xf6OGn#\xd7\xa9\xc0\xb3"\xd7\x94F$E\x9f\xc8-\xba\xe4\x118\xb5I\r2\x13?\x08\x9d\x86\x98jP\x1c\x02\xa4\t1\x96\xa1\x86\xf8\xb4\xc6\xac\x11\xe0\x13}\xb7\xbe\x08\xc8\xdf\x8d\x88\xf7\xabo\x9a=W\xa1XI\xda\x84\xf8\x10F\x1a\xe2\x9cs\xe6s\xd1l\xfb\x07\xa5F\xd1\xf6U\xbc\xdc\xa3\x97X\x15\x01\x97\x18\xdf4\xaa5,\xc5\xd6x\x95\xc0\xf1\xad\x9c<\x1d\x13\x12\xcd\x94\x0b\x06A\x86\x97$&\x12\xa99~MH\x13\xfe+\xa5\xda\xfe\x9c\xd3@\xf0\x94/$\xfaJ\x91\x8fi\xb3#\xa7t&\xcd\xe83\x1a\xc1F\xaf\x1bu\x87h\xd2<z\xfe\x05\xf9\x9c5\n\x1c\x91\x1b\x1d\x02g\x1b\xb3F!\x84i\xbb\xf0\x1e\xaf$\x8e\x9a\xad\xc2\x11+B>b\x196\x1ar\xb5\x16\x81\xb6q\xa9\x84`Z\x12\xc6\xd1xN\xd2\xb4\x11\xfcY\xac5\x93>`\xc8\xec\xcd\x91u\xce\xd6\x91\x0e\x11\x92^7B>b\xce\x8b\x90\x11\xbf\x1e\x868J\x9a\xed\xa2qX\x04\xfd\x9e^\xc3I\xc1\xe8\x82\xcbf\xfd\xb8~\x86\xd53l,\x8e\xf7G\xd4\x17J\xe4\x0f&\xa7?\xe924\x07\xa3\x9aY\t\xbd\x84Vj\x9f\xaa\x874>\xa8\x1e2\n\x05\xf1\xb9\x1e>\xe5zx\n7\x96\xc6\xbcP\xae\x82{\x01\xff\xd1\xda7\xc2\xab\xf8\x82\xc09\x7f.}\xcf\xa5\xef\xb9\xf4=\xa1\xd2\xb77#}g\xc1\xd3\x8b[\xdeFn[\xc4\xfb\xae1\xda\xd74.(cWr\xcd\xc8\xc7T\xaf\x93)\xd89\x9f\xc0\xec\xfdh>\x9e\xf1\xed\xfa\xd9$\x84\xaf\x9aY-#\x16\x90K\x81\xb3A$\xb8\xfc\x8b\xca\xf0*\xc4\t\xe8d[%\t\xcbT\xd3e7\x8a\x12\x9eB\x1bn\xe9S\xf5J\x95\xd7\xe5\xaf\xb9(\xb8<[\xe4\xe9\xaf\xa1t>,\xcf\xf9<_\xe7\xb4\xcd\x0b3C\xb7rK\xea\xb6\x94\xbe\xb5&8J\xf4\xb1\xccpN\x1e\xcb\x0c;g<\x92\x1d\xb6w\xa0\x1d5\xfb\xf6]v\xe4#\xa50S\x97C\xb8\x1aB\xbe\x03m\xba\x9d\xdc:8\x9e\x98\x91\xb9\n\xd3R\x90o\xc3\xf9\xe9\xc5x\x1a\xe29\xd9\x04\xb9}\x98Wm\xe7\xd8\xd1\xd1\xfb\xe7\xc1Q\xb0\xa3\xef<\x96\x1d\xc7\x88\xf2\xa2!\xee\xa1\x86\x98\xcf\xc3C\x87y{_\x98g\x95\xc6P4\x14ml\xac$,F\xb7`\xb8\xd7\xf1,\x14\xe0d`-\xa0\x07\x83\xafQ\x02\xf2RU`1[\xc6\x03+\x90\xa2|L\x8cE\xe8p\xe7\x97\\_\xe3\xd1\x92\xe3\xdb\xa6e\xb5n\xaf)w\x19m"R9\xc2i\x98\x13g\xab\xca\xdee\xb1\xc1U\x1d\xcfU[\xf2\xb0\xbej=\xb4\x15N\xcf\xfeY\xad\xc8\x9f\x0c\x11N\x16\x0b\x12Hc\x94\x17\xa6J\xa2\xf3\x19S\xbe\xe7+I\xc4U8\xbfE3\xb6\x12\x97\x18\xbc\xe3\xe6\xc7qNS\xb8\x12v\xb6\x0f\x022\xb9\xbb9\xa9ze1g\xa6\xf2\xdf-\x0c\t,[\x88Y\x12\xe2M]\xed\xd5\xe7\x9b\x9c\xaez"v\xfa\x97w\xc1`\xf2\xfdp\xc9G\x0f\xe5;\xe7_\xf4]C\xae~\xf6\xdd\xe3\xfan\x93;HL\x9cy\xc5\x11\x01tE\x02#\x95\x1c\x06\x16\x172\xe4P\xee\x92\x90\x06\x13\x01\xcd\x94\xc9D\xf0\x02\x82d\xa6\x1c\x80\x98\xfa\x0b\xbd\xf2\x0c\xb9)\x15\xce\xad>9\x7fE,\x83\x86N^\xd2%\x12\x14\x8a\xb0\x0c\x05!\x17r\xe3\xef\xef\x93jw\x8c\xd7\xfa,\x81m\x84T2d\xd5\x17\xcaC\x89\xc1=3rC\xd8T%\xf3\xae\xda&\x0b\x85\xdb\xe2T\xcd\xbb\x1a\xbe&`K\xc3zn\x9d-\'\xff\xdb^\xd4=\xb4\x17=F\xf3\xa3\x99\xe0\x1e\xb3\x87s\x9bz\xb8\xc2E\xac\xffX\xd6\x1e\xf92\xdf9p\xdb:\xde\x03^\xe6\x13,C\xa4~\xc1}\x8a\x8a\x80\x11\xabb\xbe\xba\xafO\xf9%\x9c;\xb4{\xf1\x81 \x9b\xfc\xd6\xdb\xa4\xf6\xdd\xe0\x0c|\xd4\xabZ\xa5d+\x11?K\x07|\x1f\x92\x06c\x8c[\xf44_\x8f\x14b\xad\xa6\xb1\xad\xc6\xda1\x0cy\x80X\xf3\x0c\xa1f8\xdf\x87E\x9a\x1a3\xd5\x8b\xac9\x8d\noA\xd5@\xe5?\xdb\xd4\rh\xf6\r4\x1c\x91\x05^1\x99\xb66\xa3\xe4N\n<\xdc\xfe\xef\r\xb0\xc2\xc4\x8e\xe1\xed\x8b\xbf\x01PK\x03\x04\x14\x00\x00\x00\x08\x00F~8]\xb3\xc5\x97{Y\xb5\x04\x00\x0bu8\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\xb4\xddks\x1b9\xf2\xe8\xe9\xf7\xfb)\x18~qbN\x84-\xb3x\xa7vf6X\tdB\xd6\xd5\x12e\xb5\xbcq\xe2\x1fl\x9bmiZ\x96\xdc\xbat\xb7\xe6\xd3/)\x89\xb4e\x02\xf8U\xd1\xde\x89\x99\x1e\xb7\x91\x89"YxP\x10*U\xfc\xe7_W\xd7\xbf\xdf\x9cM\xa7\xb7\x8d\xbf?_\\\xde\xfc\xeb\xc5\xd9\xed\xed\x97\xcd\xd7\xafo>\x9cM?On6\xae\xbeL/g-\xbf]]\x7f\x9e\xdc\xce\xfe\xf5\xfa\xd3\xeb\x9b/\xd7\xd3\xc9\xc7\x87\xa4\xcf\x17\xaf[\xcdf\xef\xf5\xe7\xc9\xf9\xe5\x8b\x7f\xff\xf3\xe1\xef\x0e\xae\xff\xfd\xcf\xab\xbb\xdb\x8b\xf3\xcb\xe9\xc1u\xe3\xe6\xee\xf3\xe7\xc9\xf5}9\xbd\xb8\xfa\xeb_/\x8a\x17\x8b\xbf8<\xfftv\xfb\xf0\x17\xaf\xff\xfd\xcf/\x93O\xd3\xa3\xe9\xed\xf1\x97Y\xc2\xec__/\xfb\xf9x\xfeyzys~u\xd9\xb8\x9e\xfe\xf6\xaf\x17\xa3b3\xecvZ\xbd\x87\xa4\x87\xa0w\xe7\xd3\xbfn\xbe\xf9s\xe3\xe6\xec\xea/\xbb>\xff\xb83;\xfc\xcdC\xff\xf3w\xf8\xeb\xd5\xd5\xef\xf3\xe6\xad\x8f\xffz\xd1|1?\xe0\xe5\xb4q\x7f\xf4\xe5\xe2\xfc\xf15\xdc^}\xd9\x99\xfev+\xd3\x8b\x8b\xd9QZ/\x1a\x93\x0f\xb7\xe7\x7fN\x0ffa\xffz\xf1\xeb\xd5\xed\xed\xd5\xe7y\xfb\xec\xd5\xdfNng\x7f\xf5\xdb\xf5\xd5\x7f\xa7\x97\x8f/cz1\x9d\x05\xcf^\xe2\x97\x95\xe8\xc7^\x9ez\x9d\xbf\xf7?\x9e\xde\xc6\x8b\xafos\xfe\xb2\xbe\xfd\xf3\xe2\xdd\xe8\xc3\'>\xfb@~\x9d\xdcL\xe5\xea\xe2\xe4\xfc\xe3\xed\xd9\xbf^\x0c^4>N\x7f\x9b\xdc]\xdc\x1e^\xfd\x15\xa6O\x9fb\xf7\xa1\xc3\x0fW\x177\x0f\xffl\xfc\xf5\x18<\xff\xfb\x0fw7\xb3\xd7\xf3\x94=;\xf0\xe7\xf3\xcb\xc7\xff\x9f\xfc\xbd\xf8\xf8\xbf\xc9h\x0f\x12\x19\xad\xa7\x8c\xd6\xf7\x19\xad\xd41\xdaO\x19\xed\xef3\x92\xaf\xaa\xf3\x94\xd1\xf9>\xa3\xd3Ldt\x9f2\xba+\xaf\xaa\x9f\xc8\xe8=e\xf4*g\xf4\x9f2\xfa\x95\xdf\xc7\xe0)c\xb0\xf2>R\x19\xc3\xa7\x8ca\xe5O\xb7h.Nas%\xa7\x95\xcaY\x9e\xf6\x95\xf3^\xa4\xce{\xb18\xf1\xc5\xea\x99o\xa7r\x16\xa7\xbeX=\xf7\xc9\xd7\xb68\xf9\xc5\xca\xd9/z\xa9\x9c\xc5\xe9/V\xce\x7f1L\xe5,\x06@\xb12\x02\x8a\xe4\xfbY\x0c\x81be\x0c\xb4:\xa9\x9c\xc5 (VFA:g1\x0c\x8a\x95q\x90v\xb9\x18\x07\xad\x95q\x90<\xa7\xad\xc58h\xad\x8e\x83\xd4\xe7\xd6ZN\x00\xab\xe3\xa0H\xe5,\xc6Ake\x1c\xb4S\xe3\xba\xb5\x18\x07\xad\xd5Y \x99\xb3\x18\x07\xad\x95q\x90\xfe\xdc\x16\xe3\xa0\xb52\x0e\xd2\xc7Y\x8c\x83\xd6\xca8\xe8\xa4\xc6uk1\x0eZ\xab\xe3 \xf9Y/\xc6Aku\x1c\xa4f\xa9\xf6b\x1c\xb4W\xc6A\xf2\xfd\xb4\x17\xe3\xa0\xbd2\x0e\xd29\x8bq\xd0^\x19\x07\xe9\x9c\xe5\xa5`e\x1c$g\xf6\xf6b\x1c\xb4W\xc6A;5\x1f\xb4\x17\xe3\xa0\xbd:\x0e\x92\xc7Y\x8c\x83\xf6\xca8H\x7f\xd6\x8bq\xd0^\x9d\x0fR\xe7\xb4\xbd\x18\x07\xed\xd5\xabB\xf2\xb5-\xc6A{e\x1c$s:\x8bq\xd0Y\x19\x07I\x0b\x9d\xc58\xe8\xac\xae\x07R\x9fAg1\x0e:\xd5\xc7Ag1\x0e:\xd5\xaf\x0b\x9d\xe5\xa2`u\x1c\xa4\xe6\x9d\xceb\x1ctV\xc6A\xfa\xb5-\xc6Agu\x1c$?\xeb\xc58\xe8\xac\xce\x07\xc9\xe3,\xc6Agu\x1c\xa4\xae\x0b\x9d\xc58\xe8\xac\x8e\x83\xd4q\xba\x8bq\xd0\xad>\x0e\xba\x8bq\xd0]\x1d\x07)s\xdd\xc58\xe8V\x1f\x07\xdd\xc58\xe8\xae^\x17\x92\xc7Y\x8c\x83n\xf5\xebBw\xb9<\xac>\x1ft\x17\xe3\xa0\xbbz]H\x8d\xd1\xeeb\x1ct\xab\x8f\x83\xeeb\x1ctW\xc7Aj\\w\x17\xe3\xa0\xbbz]H\x1d\xa7\xb7\x18\x07\xbd\xd5q\x90\x1ao\xbd\xc58\xe8\xad\x8c\x83\xe4\xda\xb2\xb7\x18\x07\xbd\x95q\x90\x9cCz\x8bq\xd0[\xbd.$\xdf\xcfb\x1c\xf4V\xc7A\xf2\xb5-\xc6Aou\x1c\xa4\xd6|\xbd\xe5\x0f\n\xd5\xaf\x0b\xbd\xc58\xe8U\x1f\x07\xbd\xc58\xe8U\xffi\xa1\xb7\x18\x07\xbd\xea\xf3A\x7f1\x0e\xfa\xd5\xd7\x07\xfd\xc58\xe8W_\x1f\xf4\x17\xe3\xa0_}>\xe8/\xc6A\xbf\xfa8\xe8/\xc6A\xbf\xfa|\xd0_\x8c\x83~\xf5\xebB\x7f1\x0e\xfa\xd5\xd7\x89\xfd\xe5\x8f\x8c\xd5\xc7A\x7f1\x0e\xfa\xd5\xc7A\x7f1\x0e\xfa\xd5\xc7\xc1`1\x0e\x06\xd5\xc7\xc1`1\x0e\x06\xd5\xc7\xc1`1\x0e\x06\xd5\xc7\xc1`1\x0e\x06\xd5\xf7\x0c\x06\x8bq0X]\x1f\xa4\xe6\x83\xc1b\x1c\x0c\xaa\xef\x1b\x0c\x16\xe3`P}\x1c\x0c\x16\xe3`P}\x1c\x0c\x96\x9b\x07\xd5\xc7\xc1`1\x0e\x06\xd5\xc7\xc1p1\x0e\x86\xd5\xc7\xc1p1\x0e\x86\xd5\xc7\xc1p1\x0e\x86\xd5\xc7\xc1p1\x0e\x86\xd5\xe7\x83\xe1b\x1c\x0c\xab\xcf\x07\xc3\xc58\x18V\x9f\x0f\x86\x8bq0\xac>\x0e\x86\x8bq0\xac>\x0e\x86\x8bq0\xac\xb1\x8b\xb4\xdcF\xaa>\x0e\x8a\xe6\xd7\x8d\xa4\xea#\xa1h.\xb7\x92\x9a\xd5\xc7B\xd1\\n&5\xab\x8f\x86\xa2\xb9\xdcNjV\xff\xf9\xb1h.7\x94\x9a\xd5GD\xd1\\n)5\xab\x8f\x89\xa2\xb9\xdcTjV\x1f\x15Es\xb9\xad\xd4\xac>.\x8a\xe6rc\xa9Y}d\x14\xcd\xe5\xd6R\xb3\xc6\xd8\xf8\xba\xc9\xb8\xba\xcb\x98\xfc)\xa2\xf8f\x9b\xb1\xc6\xd8\xf8\xba\xd1\xb8\xba\xd3\x98\xc9Z\x8e\x8d\xd5\xbd\xc6\xe4:\xba\xf8\xba\xd9\xb8\xba\xdb\x989\xd6rl\xac\xee7f\xb2\x96ccu\xc71\x93\xb5\x1c\x1b\xab{\x8e\x99\xac\xe5\xd8X\xddu\xccd-\xc7\xc6\xea\xbec:k\xb9\xf1X\xac\xee<f\xb2\x96ccu\xef1\x93\xf5u\x13\xba\xc6\xd8Xn?\x16\xab\xfb\x8f\x99\xac\xe5\xd8\xa8\xb1\x03Y,\xb7 \x8b\xd5=\xc8L\xd6rl\xd4\xd8\x85,\x96\xdb\x90Ed\x1f2\x9d\xb5\x1c\x1b\xab;\x91\x99\xac\xe5\xd8X\xdd\x8bLg-7#\x8b\x1a\xbb\x91\xc5r;\xb2\xa8\xb1\x1fY,7$\x8b\x1a;\x92E\xfb\xeb-\x8a\x1acc\xb9)Y\xac\xeeJf\xb2\x96ccu_2\x93\xb5\x1c\x1b\xab;\x93\x99\xac\xe5\xd8X\xdd\x9b\xccd-\xc7Fdw2\x9d\xb5\x1c\x1b\x91\xfd\xc9d\xd6r\x83\xb2X\xdd\xa1\xccd-\xc7\xc6\xea\x1ee&k96j\xecR\x16\xcbm\xcabu\x9f2\x93\xf5\xf5\x06V\x8d\xb1\xb1\xdc\xaa,j\xecU\x16\xcb\xcd\xcabu\xb72\x93\xb5\x1c\x1b5\xf6+\x8b\xe5\x86e\x11\xd9\xb1Lg-\xc7F\x8d=\xcbb\xb9iY\xac\xeeZf\xb2\x96ccu\xdf2\x93\xb5\x1c\x1b5v.\x8b\xe5\xd6e\xb1\xbaw\x99\xc9Z\x8e\x8d\x1a\xbb\x97\xc5r\xfb\xb2X\xdd\xbf\xccd-\xc7Fd\x073\x9d\xb5\x1c\x1b5\xf60\x8b\xe5&f\x11\xd9\xc5Lg-\xc7\xc6\xea>f:k\xb9\x91Y\xac\xeedf\xb2\x96ccu/3\x93\xb5\x1c\x1b\xab\xbb\x99\x99\xac\xe5\xd8\xa8\xb1\x9fY,74\x8b\xc8\x8ef:k96V\xf743Y_o~\xd7\x18\x1b\xcbm\xcd\xa2\xc6\xbef\xb1\xdc\xd8,j\xecl\x16\xcb\xad\xcd\xa2\xc6\xdef\xb1\xdc\xdc,j\xecn\x16\xcb\xed\xcd\xa2\xc6\xfef\xb1\xdc\xe0,j\xecp\x16\xcb-\xce\xa2\xc6\x1eg\xb1\xdc\xe4,j\xecr\x16\xcbm\xce\xa2\xc6>g\xb1\xdc\xe8,j\xect\x16\xcb\xad\xce\xa2\xc6^g\xb1\xdc\xec,j\xecv\x16\xcb\xed\xce\xa2\xc6~g\xb1\xdc\xf0,j\xecx\x16\xcb-\xcf\xa2\xc6\x9eg\xb1\xdc\xf4,j\xecz\x16\xcbm\xcfbu\xdf3\x93\xb5\x1c\x1b\xab;\x9f\xc9;\x89\xc5r\xeb\xb3X\xdd\xfb\xcc\x1ck96j\xec~\x16\xcb\xed\xcf\xa2\xc6\xfeg\xb1\xdc\x00-j\xec\x80\x16\xcb-\xd0\xa2\xc6\x1eh\xb1\xdc\x04-j\xec\x82\x16\xcbm\xd0\xa2\xc6>h\xb1\xdc\x08-j\xec\x84\x16\xcb\xad\xd0\xa2\xc6^h\xb1\xdc\x0c-j\xec\x86\x16\xcb\xed\xd0\xa2\xc6~h\xb1\xdc\x10-j\xec\x88\x16\xcb-\xd1\xa2\xc6\x9eh\xb1\xdc\x14-j\xec\x8a\x16\xcbm\xd1\xa2\xc6\xbehk\xb9/\xda\xaa\xb1/\xdaZ\xee\x8b\xb6j\xec\x8b\xb6\x96\xfb\xa2\xad\xc8\xbeh\xb2\xb2h\xb9/\xda\x8a\xec\x8b\xa6\xf6\xbeZ\xcb}\xd1\xd6\xea\xbeh\xba"i\xb9/\xda\xaa\xb1/\xdaZ\xee\x8b\xb6j\xec\x8b\xb6\x96\xfb\xa2\xad\x1a\xfb\xa2\xad\xe5\xbeh+\xb2/\x9a\x9a\x0f[\xcb}\xd1V\x8d}\xd1\xd6r_\xb4\xb5\xba/\xdaI\xddQn-\xf7E[5\xf6E[\xcb}\xd1Vd_4\xf9\xbe\x96\xfb\xa2\xad\xc8\xbeh\xfaX\xcb\xb1Qc_\xb4\xb5\xdc\x17m\xd5\xd8\x17m-\xf7E[5\xf6E[\xcb}\xd1Vd_4\xfd\xc9/\xc7Fd_4\xfd\x19.\xc7F\x8d}\xd1\xd6\xd7\x82\xcc\x1a\xfb\xa2\xad\xaf%\x99O\xfb\xa2\xaf?<\x14s?\x94\x82\xbb\xc9\xed\xe4\xdf\xff\xbc\xbe\xfa\xabq=O\x99u9\xff\xc3CA\xf9C\x17\xb7\xffzq~9\xaf\xb7?\xba\xbd\x9e\xb5\x9e\xcf\xf2n\xff\xfd\xe5\xfa\xea\xd3\xf5\xe4\xf3\xff\x9c\x7f\xfc\xe7\xeb\xdbY\x7f\xf3\xbf}\xfd\xe1)\xb7\xac\x96{9\xf9<\x8ddK>\xfb\xf6z\xf2\xe1\xf7\xe9G\x7fy{~{\xbfuys;\xb9\xfc\x10\xeb\xc6\xe5\xbb\xb9\xba\xfet|y~\x1b\x7f\x03>\x9f\xbb\x7f\xfd\xa91On\xec\xc5\xdf\x81\xe6\xd3?\\O\'\xb7\xd3\xd8q-\x9fx1\xb9\xb9=\xfe\xf21\x91\x1c\xf2\xc9{\x93\xf9\xaf\x11L.f\x9fZ$y+\x9f\x1c\xae>O\x1b\xa3\x8f\x1f\xaf\xa777\x91\xec7\xf9l\xf3{\x8dW\xa9\x0fk;\x9f\xab\x93\xdb\xb3\xe9u*y\'\x9f\xec\xceon\xaf\xcf?\xdcF2w\xab\xbc\xe4\x19\x8di\xe3\xea\xb7\xc6\xaf\xe7\xd7\xb7g\x91N\xf6\xf2\x9d\x8c>\xc5^\xf3~>\xe9dr\x1d;\xbb\x07\xf9\xac\xd9p\xfc\xe3n\xda\xd8r\x8d\x7f\x1c\x1fl\xfd\xefH\x07o\xab\xbc\xe1\xa3\xe9\xdf\x91\xd4C~\xc5\x8d\xd7\x8dw\xe7\x17\x17\x93O\xd3\xc6\x1ch\xec\x13?\x82\xf1y(\x8d\xbd\xab\x8dH\xe2\xb8\xca+\x97\xab\xcb\xdb\xd9q\x1b_\xce\xae.\xa7\x8d\xcb\xbb\xcf\xbf\xceF\xcd?.\xae>L.b\x9f\xc6q\xbe\xcf\xf1\xd5_\x977g\xe7_\x1a\xff\x18\xc7\xb2\xdf\xe5\xb3\x0f\xa7\x9ff\xd4^\x1f\xcd\x7f\x9b\'\x92}\x92\xcf\x9e^^_]\\|\x9e^\xde\xfe\xcf\xfc\xf7\x81\xeeb\xe0~\xc9w\xf1\xff\x8e\xcb\xc6\xd1l\x9a\x99^\x9e_~\xfa?\x8d\x9d\xab\x9b\x9b\xf90\x9e|\xf92\x9d\xcd\x9a\xb1\xd7tZ\xab\xc3\xd9\xbf\xc9\xd1\xecC?<\xbf\xf9\xbd\xf1\xdb\xecc\xbf\xbanL.>\\\x9d]]D\xfa~_\xabo\xf9\xe5\xb01\x9bf\xee.n\x1b\x1ff\x9f\xdf\xa7\xab\xeb\xd8|5\x82\xebS\x85\x17|w\xf9qz}yuw}~s6\xff\xb4cG\x81+\xd9\xf7/\xfd\xea\xee\xd3Y\xe3\xf3\xd5\xf5\x0c\xc1\xd9\xe4\xb2\xd1j\xfc5\x9d\xfe\x1e;\x7f#\xb8\xc8}\xdf\xf1\xd9\xf4f6\xb4\'\xe7\x97\xb1\xbe\xe0J\x17\xf9|o\x16\xff\xda\xf8\x18\x1f\xa2#\xb8\x02V\xf8xo>_\xfd>k\x8cu\x0e\xd7\xc7\n\x9d\x7f<\x9f\xfc:\xbd\x9dF?Z\xb8\x88f?\x8eY\xf7\xe7\xf3+d\xe3\xf6\xfeK\xf4s\x81\x8b\xecw\x9d\x1fN\x7f\x9b^_O.\x1a\xb3\xd5\xc6\xe4\xf2\xfc\xbf\x0f\x97\xe0X\xb7p\xf9Mu\xfb\xf0\x1b\x80\xf1\x0b\xfa\x08\xae\xc9\xdf\x7f\xc8\xb3\xf7;\x9f"f\x1fG\xac3\xb8H\xe7\x87\xd8lB\x8e\xf5\t\xd7\xee\xe4\xb4\x10\xeb\x0b\xae\xe6\x89\x11\x15\xb6\xde5\xce/\x7f{\xfc\x05\xcbX\xb7p}\xff\xae\xdb\xd9R\xe5\xfc\xd3\xec"<\xb9\xfc\xd8\x18\x9f_O?^\xc6WK#X\x01|\xd7\xed\xc1\xf5\xf4\xcf\xf3\xab\xbb\x9b\xf9\xcb\x0e\xb3\x05MbB\x84\x05\xc2w\x9d\xce\x96&\x8d\x7fLn\xbf\x9e\xa6\xd8en\x04k\x86\xef\xfa\xdc\xbbj\xdc\xdc\x7f\xfe2\xfb\xf9\xe3fv\xaa.\xe6\xcb\xd4\xd9\x8f&\xb7g\xb3\x17\x1e\xeb\x1cV\x15O\xcb\x89X&\xac$\xbe\x7fY\xf3\xdfbm\xdc\xfc5[tG\xcf\x06,/\xbe\xeb\xcd?\\\x9d\x1b\xb7W\rw>\xf9tyus{\xfe\xa1\xe1\xff\x9c\\\xdc%q\xc3Z\xe3\xbb\x03\x9c<\xfc\xd6m\xe3\xe2*>v`\xe9\xf1\xfd{\x7f\\\x07\xcd`\x7f\xf9f\x14M\xbf\x9c\xdf\\}\x8c\xcf\x9e\xb08\xf9\xae\xff\xd3\xe9\xe4\xa1\xf7\xf9O&\xf3\x9e\xc7\xf3\x1fmR\x17\xd3z\x8b\x96\xe5\xb4?[L\xcdV\xf1\x0f\x9f\xee\xec_\x17\x13\xd5\x97\xd9_\xcc\x8e3\xf3[\xed\xe0\xf5\x168\xdf\x9a\xbb\x9e\xbd\x80Y\xaf\xb1Nae\x13\xf9!\xa2q~\xd3\x98]\xcb\xcf?\'~\x88+\xeb\xadkF\x97\xf7\xf3\x97\xf8\xf1\xfa\xee\xd3|v<\x7f\xfci\xb8q\xf68M\xfc?\xb1\x03\xd4[\xd2\x84\xd9\x870\x9d-\xeb>.\x16\xd8\xb1.\xeb-f\xf6\x1f~\xa0\xbb~~i\xbcy<\xbf\xff8\xfa2\xfdp\xfe\xdb}l6*\xeb\xads\xc2d\xfa\xf9\xea\xcb\xed\xfd\xecC\x89uVo\x81\xa3\xd3?g\xaf\xb9\xca\xca\xae\xac\xb7\xb8y\xfc0jL\x9be\xbd\xe5\xcd\xd3\xe7\xd9\xb8zv\x9cX\xbf\xf5V6rw}=\xe7\x97Y\x81\x94\xf5\x165O\xf3\xde?f\xa0\x7f\xfft\x13\x1d\x00\xf5\x964\xe5\xeeV\xac\x93zK\x99\xf0\xf5U\x9d_~\x98-\xc3\xa3/\xac\xdeR&L\'\x17\xb7g\x1f&\xb3\xc14\x7fz\xc4\xec\xbc|\xb9\xfarw\x91\xba~\x94\xeb/n\x1e\x7f~L-\xf2\xcbz\xcb\x9br>\xbd\x9e]\xcc\xd64\x89uMYo]\xb3{\xfe\xe9z2\x1bB\xf97O\xcb\x9af\xb1\xf1\xb5\xd3\x87\xa5\x97Ln\xa6\x8b\x85R\xdd\x1fUKZ\xf1\xd0\xe1\xaa\xfd\xf4Z\xc2\xdag\xadwU\xe1\xe7\xd9\x92VNU\xde\x1e\xfe\xf0X\xd2\x8aj\x9dw\x97\xfeq\xb2\xa4\xf5\xd5:\x87\xcb\xfc\x80Y\xd2\x12\xac\xde\x87H?r\x96\xb4"\xa3\xc3U\xfd!\xb4\xa4\xf5Y\xe5\x03\xe5.\n\xb4\x0e\xc3\x93\x95\xfdA\xb5\xa4\xbd\xa6\x9a\x03<\xfe\xa3\xab\xd0"\xad\xfa,\x11\xeb\x9dVhU\xc73\xfdx+\xb4n\xa3\x03\xd5\xfb\x81Oh\xfdF\x87\xab\xf6\x83\xb0\xd0\xca\x8e\x0eS\xe9Gc\x81e\xde\xf8\xe1.\xd5uc+\xb6\xc8\x17X\xc3}\xb7\x99?;\x95[\xb3\xb9\xfd\xef\x87\xd7\x19\xeb\x0e\x96n\x87\xd3\xc7\xcb\xeb\xc3\x86\xf6\xc3\xf99\x9fw\x17\xeb\x89\x96l8\xb0+\xef\x80\n-\xe6\xf0P\xb9=Q\xa1U\x1e\xf5^a\xcb\\h\xd5G\xc7\xc8\xff\xa4/\xb4\xec\xa3\xee\xabnG\t-\x03\xe9@\xf9\x9f\xb4\x84V\x858\xcb\xe4\xf7o\xe4GW\x88\xb5\xf7H\xe4G\x17\x89uvM\xe4G\x97\x8a\xf5\xb7\x08\xe4GW\x89?w\xebF~t9Ym3G~t\x19Ye\xabD~t\xedX}#B~t\xddX\xe1G|\xf9\xd1%c\xf5\x1fV\xe5G\x17\x8e\xbc\xbf ?\xbax\x8c\xef8\xb8\x1f]-V\xda\x83p\xb8jlm4\xfc\xdf\x93\xcf\xe7\x97\x8f\x1e\x0f\xa7\xb35\xc6L\xdf\xfcx\x87\x0fk\xd1\x9b\xff\xf3\xf4\x87\xd9O?73\xa4\x1f\xceR\'\xc3\xe1\xca\xb1\xce\xc1\x12\xc7\xc0\xe5b\x95c\x8c\xcbW;\xa3r6\xc2~\xf92\xbd\xbem\xec\x8e\xcb\xd7\x87[\xda8\xbe\x98MK\xb1\x83\xe2\xe2\xb1\xdaA\x17\xf3\xdfr\xba\xfd0\x9b\xe9n\xce\x7f;\xff\x90\xfa\xe9\xcb\xd1\xbea\xcd\x8ft\xd2\x98\xfc99\xbf\x98\xfcz1m\xfc\xf6\xf0\x03\xed\xe3)\x8d\x1d\x9a\xb6\x14\x9b\xed\x8d\xf9{z\xba\xe1q\xbe|\x87\xcb\xbf\x88uJ\xfb\x89\xab\x9d~\xbd\xb52\xef~N\xe0\xe8\xee\xfa\xcf\xe9\xfc>\xd0\xfc#<x,\x1b\x8b\x1d\x0b\x97\xad\x897\xf0\xaaqt\xfe\xb89?\xfbx\xa6\xf1\xd5\xb5\xc3\x85\xeaj\xe7O\x17\xba\xd9\xdf>]\xebb\xfd\xe2\x125\xf9\xa2k\x8d+\\\xa5&\x0f\xb3\xfc\xab$Q\\\xa2&\xfb\x9e]"\x7f;\x9f?\x82v>\x94?Oo\xcf\xaeb?(9\\\x9a\xd2\x8b\x9f\xdf\x9d\xbb\xbc\x8a\xbf\xfa\x1f]\x98\xd6\xde\xbbw?\xbaT\xad\xb9s\xecp\xa1ZmN\xf9\xcf\xf4\xc3l\x01>\xf9\xfc\xe5"\xfa9\xe2\n\xb5\xcaQ\x1enT\xccVf\xa9m0\x87\x8b\xd2\x1f\xbd\x1c\xa4wd\x1c\xae@\xab\x1c{q\x1f\xf0f\xf1N?\xccf\xbb\xd9\'\x1b\xbd\x0f\xe8p5Z\xe5\x90\xef\xceo\xee\xe6\xfbq\xb3\x1fb\'\xd7\xa9:\xd9\x1f]\x92\xe2}\x01\x87+\xd1*\xef\xe5\xeb\x19\xfb\xc5\x1d..t\xf3+\xdbv\xf4\x92\x80+\xd3:\xa7\xec\xe8a\xec\xcf\xfe\xfe\xc3\xf4\xfc\xcf\x19\xf1\xc9mcg\xf2\xeb\xd5\xec\'\x9b\xf8\x1e\x94\xc3\xc5\xea\x0f\xbdc\x7f{\x15;(._k\x1f4V\x1a\x8d\xab\xd9\x1fzk\xa3\xd8\xc9\xf4?em\xfb\xfc\x98\xff\xf8&>\xb6\x9e\xf6?e\x89\x9b|\x9f\x12}\x9f?e\xc9\x9b<\xa6\xfe\x11;\xe6OY\xf1\x1e\xce\x16O\xb3\xb6\xf9Q\x9e\x1f\xfe\xfa1:v\xe0\x9f\xb2\xe0M\xbe\xd9\xad\xbd\x10;(.u+]\xab\x1e\xa6\x83\xf9\x15\xffi>\xf8\xc7c\xbdqt\x1c\xe1:\xb8\xca\x11\xe7\xe5\xef\x8f;F\x8bY\xa71\xfd&gq\x0f)v\xfc\x1f\xdd\xd2\xadt\x9b\xd6\xe3"\xb9\xd6\xd5\xf9i\xbe\xddr\xb1C\xad\xbfn\xde\x9d\\\xce.\x87\x17\xf7\x8d\xf9\x9a\xf9\xd3\xe5\xec\xc4]\xd7XI\xfb\xf5W\xd2s\x1e\xf3#\xd6;\xde\x8fn\x00\x8f\x9e6n\x1a{W\xf1;\x99\x9e\x96\xd7\xdf\x1e\xe0\xe57?\x0f\xcc\x8f5\xebt\xf9\xea\xd7\xd8D\xf5\xb4\xfa\xae~\xecz\xb7\xf8=-\xc2\xab\x1f\xb8\xfaf\x9c\xa7\x95x\x8dO:\xbf\x1d\xeei5^\xfdH\x95\xf6\x9d<\xad\xcb\xeb\x9fG\xfe\x99\xdc\xd3\x82\xbc\xfaA\xeb\xec\xc5{Z\x94\xd7x\xafU\xb6\x08<-\xcd\xab\x1f\xaf\xf6\xcf\xaa\x9e\x16\xed\xf5\xcf\xeb\xe8p\xbc\xdc\xfb\x8fO\xed\xb4h\xaf~\xccz5\x16\x9e\xd6\xeb\xf5Ol\xbc>\xc1\xd3\x1a}\xddw\x98\xa8TPZ\xad\xd7?\x8b\xbcU\xaf\xb4\\\xaf\xf1&\xf9\x1e\x84\xd2B}\x8d\x0bI\x8d\xab\xb4\xd2\x9a\xbd\xfa\xe1\xeb\xdf\xa9SZ\xbcW?8\xdf\x1eQZ\xb0W?X\xfcF\x89\xd2\xe2\xbc\x1e\x0e.\xc3SZ\x9b\xff\xd8\x1a\xa4BA\x9e\xd2\xea|\x9d\xc1\xfb3n\xba*-\xe8\xeb\xbf\xb0j[\xbeJ\xcb\xfb\xb5g\xc8\xc4dE\xab\xfa\x1f\x1b\x03\xe9\xb2E\xa5\xe5\xfd\x8f\x1d8S\xc0\xa8?o\xd9_\xb5\xb6P\x7f\xdej\xbfJ\x95\xa1\xfe\xbc5~\xb6TO\x7f\xde\xb2\xbej\xd1\x9e\xfe\xbc\xf5}\xb5\xba\x08\xfd\xf9\x0b|\xbc\xb1\xa4?o}_\xb5\nJ\x7f\xde\xda\xbeZ\x9d\xa2\xfe\xbc\xc5}\xa5\x8aE\xa5\x05}k\xe3\xd9E!\xba\x1c\x9a\xcck\x03\xd27}\x95\x16\xf0\xc9c\xe8\xf9\xf5\xcd\xed\xaby|\xe3v\xd1\xba\x18\x94\x8d\x0fW\x9f\xbf\xcc\x8e\x98\x12A\x8b\xf7\xe4A\x97\x7f5\x137\xeb\xfd\xf1\xca\xf4q\xf6\xa3\xd1}\xe3\x1f\x1f\'\xf7\xf1U\x10\xad\xe0\xeb\xbd\xc5\xd9\xe7z\x9d,\x810Z\xbd\'\x8f\xb5\x7fw\xfba\xfe\xc8\x8e\x8f\xb3\x91\x9f\xea\x9cV\xe9U\xc6\x03.

In [12]:
df_result1 = df_result.reindex(sorted(df_result.columns, reverse=True), axis=1)  # Sort columns in reverse alphabetical order (Z -> A)

In [13]:
df_result1

,trackedEntityInstance,program_name,program_id,orgUnit_id,lastUpdated,enrollment_status,enrollment_date,created,[TB Screening] Year of last TB Treatment,[TB Screening] Weight loss,...,Home Address,GEN - Sex,GEN - Name,GEN - Date of birth is estimated,GEN - Date of birth,GEN - Contact phone number (local),Father Name,District,Country of origin,Age
0,h29C0X4VZ6v,Registration and Screening,UZF0HrTlps0,KqjORlUe8Yc,2026-06-04T05:17:31.859,ACTIVE,None,2026-06-02T05:13:41.473,NaN,NaN,...,"46, Thayat Myaing St",MALE,Thein Htay Aung,NaN,2004-06-02,09753122470,U Hla Moe,Mayangon,NaN,21
1,zySTcqaFVh8,Registration and Screening,UZF0HrTlps0,KqjORlUe8Yc,2026-06-04T05:17:54.397,ACTIVE,None,2026-06-02T05:23:33.088,NaN,NaN,...,"99, Pazuntaung 3st,",MALE,Min Min Tun,NaN,1995-01-05,09668009524,U Aye Naing,Mayangon,NaN,31
2,ZFerVs0glZL,Registration and Screening,UZF0HrTlps0,KqjORlUe8Yc,2026-06-04T05:18:59.291,ACTIVE,None,2026-06-02T05:26:21.864,NaN,NaN,...,"Zayyamingalar 2st,\n",FEMALE,Ha Li Mar B,NaN,1981-02-26,09972977195,U Tha Mar,Mayangon,NaN,45
3,pT1gXZAmImn,Registration and Screening,UZF0HrTlps0,KqjORlUe8Yc,2026-06-04T05:19:44.128,ACTIVE,None,2026-06-02T05:28:51.847,NaN,NaN,...,"No.142, ThuKhaMyaing 2st,",MALE,Kyaw Soe Min,NaN,1991-12-01,0925418958,U Aung Naing,Mayangon,NaN,34
4,UyxHvIrEdsG,Registration and Screening,UZF0HrTlps0,KqjORlUe8Yc,2026-06-04T05:20:24.091,ACTIVE,None,2026-06-02T05:32:22.607,NaN,NaN,...,"No.162, Aung Chan Thar St,",FEMALE,Phyu Phyu Win,NaN,1964-06-01,09xxxxxxx,U Kyaw Min,Mayangon,NaN,62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,xYpfsEjE5B2,TB Case Surveillance,Lt6P15ps7f6,AQpmqMcXgPN,2026-09-12T07:47:59.801,ACTIVE,None,2026-09-12T07:41:15.289,NaN,NaN,...,NaN,FEMALE,lone lay,NaN,1999-01-11,09xxxxxxx,lone lone,Amarapura,NaN,27
421,rsrnxQ0iFeA,TB Case Surveillance,Lt6P15ps7f6,rTTCKrLpxTB,2026-09-15T07:40:20.787,ACTIVE,None,2026-09-15T07:33:47.161,NaN,NaN,...,NaN,MALE,TEST_TPS,NaN,2000-01-15,09xxxxxxxxx,TPS FATHER,Kamayut,NaN,26
422,ueaJQJ3ZMYq,TB Case Surveillance,Lt6P15ps7f6,OeZsFpNKLP5,2026-08-15T09:40:36.754,COMPLETED,None,2026-08-15T07:17:03.011,NaN,NaN,...,Lanmadaw\n304,MALE,Thet Ko,NaN,2000-12-19,09976056279,Father Thet Ko,Monywa,NaN,25
423,MeHZdcgLuZw,TB Case Surveillance,Lt6P15ps7f6,mPwLv1cjror,2026-08-16T04:08:05.801,ACTIVE,None,2026-08-16T03:04:55.731,NaN,NaN,...,NaN,MALE,Mingalar,NaN,2000-01-01,09xxxxxxxxx,father mingalar,Aunglan,NaN,26
424,iY92KxJrh5V,TB Household Contact Investigation,cQsXTtAJ3HW,KqjORlUe8Yc,2026-09-23T08:01:51.827,ACTIVE,None,2026-09-23T07:56:06.963,NaN,NaN,...,"No. 843, Muditar Housing, 2 Ward, Baho Road, M...",MALE,Thet Ko Ko,true,1992-09-23,09265591687,U Phoe,Mayangon,NaN,34

In [14]:
df_result2 = df_result1.reindex(sorted(df_result1.columns), axis=1)  # Sort columns alphabetically (A -> Z)
df_result2

,Age,Country of origin,District,Father Name,GEN - Contact phone number (local),GEN - Date of birth,GEN - Date of birth is estimated,GEN - Name,GEN - Sex,Home Address,...,[TB Screening] Weight loss,[TB Screening] Year of last TB Treatment,created,enrollment_date,enrollment_status,lastUpdated,orgUnit_id,program_id,program_name,trackedEntityInstance
0,21,NaN,Mayangon,U Hla Moe,09753122470,2004-06-02,NaN,Thein Htay Aung,MALE,"46, Thayat Myaing St",...,NaN,NaN,2026-06-02T05:13:41.473,None,ACTIVE,2026-06-04T05:17:31.859,KqjORlUe8Yc,UZF0HrTlps0,Registration and Screening,h29C0X4VZ6v
1,31,NaN,Mayangon,U Aye Naing,09668009524,1995-01-05,NaN,Min Min Tun,MALE,"99, Pazuntaung 3st,",...,NaN,NaN,2026-06-02T05:23:33.088,None,ACTIVE,2026-06-04T05:17:54.397,KqjORlUe8Yc,UZF0HrTlps0,Registration and Screening,zySTcqaFVh8
2,45,NaN,Mayangon,U Tha Mar,09972977195,1981-02-26,NaN,Ha Li Mar B,FEMALE,"Zayyamingalar 2st,\n",...,NaN,NaN,2026-06-02T05:26:21.864,None,ACTIVE,2026-06-04T05:18:59.291,KqjORlUe8Yc,UZF0HrTlps0,Registration and Screening,ZFerVs0glZL
3,34,NaN,Mayangon,U Aung Naing,0925418958,1991-12-01,NaN,Kyaw Soe Min,MALE,"No.142, ThuKhaMyaing 2st,",...,NaN,NaN,2026-06-02T05:28:51.847,None,ACTIVE,2026-06-04T05:19:44.128,KqjORlUe8Yc,UZF0HrTlps0,Registration and Screening,pT1gXZAmImn
4,62,NaN,Mayangon,U Kyaw Min,09xxxxxxx,1964-06-01,NaN,Phyu Phyu Win,FEMALE,"No.162, Aung Chan Thar St,",...,NaN,NaN,2026-06-02T05:32:22.607,None,ACTIVE,2026-06-04T05:20:24.091,KqjORlUe8Yc,UZF0HrTlps0,Registration and Screening,UyxHvIrEdsG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,27,NaN,Amarapura,lone lone,09xxxxxxx,1999-01-11,NaN,lone lay,FEMALE,NaN,...,NaN,NaN,2026-09-12T07:41:15.289,None,ACTIVE,2026-09-12T07:47:59.801,AQpmqMcXgPN,Lt6P15ps7f6,TB Case Surveillance,xYpfsEjE5B2
421,26,NaN,Kamayut,TPS FATHER,09xxxxxxxxx,2000-01-15,NaN,TEST_TPS,MALE,NaN,...,NaN,NaN,2026-09-15T07:33:47.161,None,ACTIVE,2026-09-15T07:40:20.787,rTTCKrLpxTB,Lt6P15ps7f6,TB Case Surveillance,rsrnxQ0iFeA
422,25,NaN,Monywa,Father Thet Ko,09976056279,2000-12-19,NaN,Thet Ko,MALE,Lanmadaw\n304,...,NaN,NaN,2026-08-15T07:17:03.011,None,COMPLETED,2026-08-15T09:40:36.754,OeZsFpNKLP5,Lt6P15ps7f6,TB Case Surveillance,ueaJQJ3ZMYq
423,26,NaN,Aunglan,father mingalar,09xxxxxxxxx,2000-01-01,NaN,Mingalar,MALE,NaN,...,NaN,NaN,2026-08-16T03:04:55.731,None,ACTIVE,2026-08-16T04:08:05.801,mPwLv1cjror,Lt6P15ps7f6,TB Case Surveillance,MeHZdcgLuZw
424,34,NaN,Mayangon,U Phoe,09265591687,1992-09-23,true,Thet Ko Ko,MALE,"No. 843, Muditar Housing, 2 Ward, Baho Road, M...",...,NaN,NaN,2026-09-23T07:56:06.963,None,ACTIVE,2026-09-23T08:01:51.827,KqjORlUe8Yc,cQsXTtAJ3HW,TB Household Contact Investigation,iY92KxJrh5V

In [16]:
print(list(df_result2.columns))

['Age', 'Country of origin', 'District', 'Father Name', 'GEN - Contact phone number (local)', 'GEN - Date of birth', 'GEN - Date of birth is estimated', 'GEN - Name', 'GEN - Sex', 'Home Address', 'NRC No.', 'Nationality', 'Org Unit Name', 'Passport number', 'Region/State', 'Relationship with index', 'Township (T)', 'Tracker Id', 'Unique ID (UPI)', 'Unique ID (UPI) - Index Case', 'Village', 'Ward', 'Ward / Village tract', '[01. Screening and Case History] Activity Notes', '[01. Screening and Case History] Age (at screening)', '[01. Screening and Case History] Any TB drug resistance history?', '[01. Screening and Case History] BMI', '[01. Screening and Case History] Breathlessness', '[01. Screening and Case History] CXR result', '[01. Screening and Case History] CXR result category', '[01. Screening and Case History] CXR screening date', '[01. Screening and Case History] CXR screening done', '[01. Screening and Case History] CXR screening facility type', '[01. Screening and Case History] Chest pain', '[01. Screening and Case History] Cough more than 2 weeks', '[01. Screening and Case History] Current activity', '[01. Screening and Case History] Fatigue and Tiredness', '[01. Screening and Case History] Fever more than 2 weeks', '[01. Screening and Case History] Haemoptysis', '[01. Screening and Case History] Healthcare worker population', '[01. Screening and Case History] Height (in inches)', '[01. Screening and Case History] Household Contact', '[01. Screening and Case History] Loss of appetite', '[01. Screening and Case History] Migrant population', '[01. Screening and Case History] Night sweats', '[01. Screening and Case History] No symptoms related with TB', '[01. Screening and Case History] Number of previous TB episodes', '[01. Screening and Case History] Other symptoms related with TB', '[01. Screening and Case History] Previous TB History', '[01. Screening and Case History] Previous TB regimen', '[01. Screening and Case History] Referral activity', '[01. Screening and Case History] Referral organization', '[01. Screening and Case History] TB CS - HIV infection', '[01. Screening and Case History] TB CS - HIV status date', '[01. Screening and Case History] TB CS - Registration - Type of patient in last TB Treatment', '[01. Screening and Case History] TB CS - Risk factor alcohol', '[01. Screening and Case History] TB CS - Risk factor diabetes', '[01. Screening and Case History] TB CS - Risk factor smoking', '[01. Screening and Case History] TB CS - Risk factor undernourishment', '[01. Screening and Case History] Type of CXR', '[01. Screening and Case History] Weight (in kgs)', '[01. Screening and Case History] Weight loss', '[01. Screening and Case History] Year of last TB Treatment', '[02. Examination Request and Results] Date of Sample Received at Laboratory', '[02. Examination Request and Results] Date of specimen collected', '[02. Examination Request and Results] Name of laboratory examination facility', '[02. Examination Request and Results] Reason for Xpert MTB/XDR request', '[02. Examination Request and Results] Reject sample', '[02. Examination Request and Results] Result data available for dispatch', '[02. Examination Request and Results] Result date', '[02. Examination Request and Results] Result dispatch date', '[02. Examination Request and Results] Samples received (number)', '[02. Examination Request and Results] Specimen type', '[02. Examination Request and Results] TB CS - Resistance classification', '[02. Examination Request and Results] TB-LAB - Sample ID', '[02. Examination Request and Results] TB-LAB - Xpert MTB/RIF Ultra', '[02. Examination Request and Results] TB-LAB - Xpert MTB/RIF Ultra result', '[02. Examination Request and Results] Visual appearance', '[02. Examination Request and Results] Xpert MTB/XDR', '[02. Examination Request and Results] Xpert MTB/XDR (Examination)', '[02. Examination Request and Results] Xpert MTB/XDR Result for Am', '[02. Examination Request and Results] Xpert MTB/XDR Result for Cm', '[02. Examination Request and Results] Xpert MTB/XDR Result for Eto', '[02. Examination Request and Results] Xpert MTB/XDR Result for Fq', '[02. Examination Request and Results] Xpert MTB/XDR Result for INH', '[02. Examination Request and Results] Xpert MTB/XDR Result for Km', '[03. TB Diagnosis] Enroll to TB Case Surveillance Program', '[03. TB Diagnosis] TB CS - Confirmation method', '[03. TB Diagnosis] TB CS - Diagnosis date', '[03. TB Diagnosis] TB CS - Diagnostic note', '[03. TB Diagnosis] TB CS - Manually assigned resistance classification', '[03. TB Diagnosis] TB CS - Reassign resistance classification', '[03. TB Diagnosis] TB CS - Resistance classification', '[03. TB Diagnosis] TB CS - Site of disease', '[03. TB Diagnosis] TB CS Diagnosis', '[03. TB Diagnosis] Type of TB patient', '[1. Screening, Diagnosis and Notification] Age (at screening)', '[1. Screening, Diagnosis and Notification] Any TB drug resistance history?', '[1. Screening, Diagnosis and Notification] BMI', '[1. Screening, Diagnosis and Notification] Breathlessness', '[1. Screening, Diagnosis and Notification] CXR result', '[1. Screening, Diagnosis and Notification] CXR result category', '[1. Screening, Diagnosis and Notification] CXR screening date', '[1. Screening, Diagnosis and Notification] CXR screening done', '[1. Screening, Diagnosis and Notification] CXR screening facility type', '[1. Screening, Diagnosis and Notification] Cough more than 2 weeks', '[1. Screening, Diagnosis and Notification] Current activity', '[1. Screening, Diagnosis and Notification] Fatigue and Tiredness', '[1. Screening, Diagnosis and Notification] Fever more than 2 weeks', '[1. Screening, Diagnosis and Notification] Haemoptysis', '[1. Screening, Diagnosis and Notification] Healthcare worker population', '[1. Screening, Diagnosis and Notification] Height (in inches)', '[1. Screening, Diagnosis and Notification] Loss of appetite', '[1. Screening, Diagnosis and Notification] Migrant population', '[1. Screening, Diagnosis and Notification] Night sweats', '[1. Screening, Diagnosis and Notification] Number of previous TB episodes', '[1. Screening, Diagnosis and Notification] Other symptoms related with TB', '[1. Screening, Diagnosis and Notification] Previous TB History', '[1. Screening, Diagnosis and Notification] Previous TB regimen', '[1. Screening, Diagnosis and Notification] Referral activity', '[1. Screening, Diagnosis and Notification] Referral organization', '[1. Screening, Diagnosis and Notification] Started on Treatment', '[1. Screening, Diagnosis and Notification] TB CS - ART patient ID', '[1. Screening, Diagnosis and Notification] TB CS - Case notification', '[1. Screening, Diagnosis and Notification] TB CS - Confirmation method', '[1. Screening, Diagnosis and Notification] TB CS - Diagnosis date', '[1. Screening, Diagnosis and Notification] TB CS - Diagnostic note', '[1. Screening, Diagnosis and Notification] TB CS - HIV infection', '[1. Screening, Diagnosis and Notification] TB CS - HIV status date', '[1. Screening, Diagnosis and Notification] TB CS - Manually assigned resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Notification date', '[1. Screening, Diagnosis and Notification] TB CS - Reassign resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Registration - Type of patient in last TB Treatment', '[1. Screening, Diagnosis and Notification] TB CS - Resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor alcohol', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor diabetes', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor smoking', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor undernourishment', '[1. Screening, Diagnosis and Notification] TB CS - Site of disease', '[1. Screening, Diagnosis and Notification] Type of CXR', '[1. Screening, Diagnosis and Notification] Type of TB patient', '[1. Screening, Diagnosis and Notification] Weight (in kgs)', '[1. Screening, Diagnosis and Notification] Weight loss', '[1. Screening, Diagnosis and Notification] Year of last TB Treatment', '[2. TB Treatment] TB CS - Diagnosis date', '[2. TB Treatment] TB CS - First-line treatment regimen composition', '[2. TB Treatment] TB CS - First-line treatment start date', '[2. TB Treatment] TB CS - Manually assigned resistance classification', '[2. TB Treatment] TB CS - Outcome due date', '[2. TB Treatment] TB CS - Reassign resistance classification', '[2. TB Treatment] TB CS - Resistance at diagnosis', '[2. TB Treatment] TB CS - Resistance classification', '[2. TB Treatment] TB CS - Treatment initiation delay (days)', '[2. TB Treatment] TB CS - Treatment regimen', '[4. Outcome] TB CS - Treatment outcome', '[4. Outcome] TB CS - Treatment outcome delay (weeks)', '[Screening & Testing] BMI', '[Screening & Testing] CXR result category', '[Screening & Testing] CXR screening date', '[Screening & Testing] CXR screening done', '[Screening & Testing] Enroll to Diagnostic Evaluation', '[Screening & Testing] Height (in inches)', '[Screening & Testing] Previous TB History', '[Screening & Testing] Referral activity', '[Screening & Testing] Referral organization', '[Screening & Testing] TB CS - HIV infection', '[Screening & Testing] TB CS - Risk factor alcohol', '[Screening & Testing] TB CS - Risk factor diabetes', '[Screening & Testing] TB CS - Risk factor smoking', '[Screening & Testing] TB CS - Risk factor undernourishment', '[Screening & Testing] TB-HH - Active TB test result', '[Screening & Testing] TB-HH - Active TB testing', '[Screening & Testing] TB-HH - Screening', '[Screening & Testing] Weight (in kgs)', '[TB Screening] Age (at screening)', '[TB Screening] Any TB drug resistance history?', '[TB Screening] BMI', '[TB Screening] Breathlessness', '[TB Screening] CXR result', '[TB Screening] CXR result category', '[TB Screening] CXR screening date', '[TB Screening] CXR screening done', '[TB Screening] CXR screening facility type', '[TB Screening] Chest pain', '[TB Screening] Cough more than 2 weeks', '[TB Screening] Current activity', '[TB Screening] Enroll to Diagnostic Evaluation', '[TB Screening] Fatigue and Tiredness', '[TB Screening] Fever more than 2 weeks', '[TB Screening] Haemoptysis', '[TB Screening] Healthcare worker population', '[TB Screening] Height (in inches)', '[TB Screening] Household Contact', '[TB Screening] Loss of appetite', '[TB Screening] Migrant population', '[TB Screening] Night sweats', '[TB Screening] No symptoms related with TB', '[TB Screening] Number of previous TB episodes', '[TB Screening] Other referral organisation (Specify)', '[TB Screening] Other symptoms related with TB', '[TB Screening] Previous TB History', '[TB Screening] Previous TB regimen', '[TB Screening] Referral activity', '[TB Screening] Referral organization', '[TB Screening] Specify other symptoms', '[TB Screening] TB CS - HIV infection', '[TB Screening] TB CS - HIV status date', '[TB Screening] TB CS - Registration - Type of patient in last TB Treatment', '[TB Screening] TB CS - Risk factor alcohol', '[TB Screening] TB CS - Risk factor diabetes', '[TB Screening] TB CS - Risk factor smoking', '[TB Screening] TB CS - Risk factor undernourishment', '[TB Screening] Type of CXR', '[TB Screening] Weight (in kgs)', '[TB Screening] Weight loss', '[TB Screening] Year of last TB Treatment', 'created', 'enrollment_date', 'enrollment_status', 'lastUpdated', 'orgUnit_id', 'program_id', 'program_name', 'trackedEntityInstance']

In [ ]:
'lastUpdated','Org Unit Name','Region/State','District','Township (T)','Ward','Unique ID (UPI)','GEN - Name', 'GEN - Sex','Age','GEN - Contact phone number (local)'

In [ ]:
['Age', 'Country of origin', 'District', 'Father Name', 'GEN - Contact phone number (local)', 'GEN - Date of birth', 'GEN - Date of birth is estimated', 'GEN - Name', 'GEN - Sex', 'Home Address', 'NRC No.', 'Nationality', 'Org Unit Name', 'Passport number', 'Region/State', 'Relationship with index', 'Township (T)', 'Tracker Id', 'Unique ID (UPI)', 'Unique ID (UPI) - Index Case', 'Village', 'Ward', 'Ward / Village tract', '[01. Screening and Case History] Activity Notes', '[01. Screening and Case History] Age (at screening)', '[01. Screening and Case History] Any TB drug resistance history?', '[01. Screening and Case History] BMI', '[01. Screening and Case History] Breathlessness', '[01. Screening and Case History] CXR result', '[01. Screening and Case History] CXR result category', '[01. Screening and Case History] CXR screening date', '[01. Screening and Case History] CXR screening done', '[01. Screening and Case History] CXR screening facility type', '[01. Screening and Case History] Chest pain', '[01. Screening and Case History] Cough more than 2 weeks', '[01. Screening and Case History] Current activity', '[01. Screening and Case History] Fatigue and Tiredness', '[01. Screening and Case History] Fever more than 2 weeks', '[01. Screening and Case History] Haemoptysis', '[01. Screening and Case History] Healthcare worker population', '[01. Screening and Case History] Height (in inches)', '[01. Screening and Case History] Household Contact', '[01. Screening and Case History] Loss of appetite', '[01. Screening and Case History] Migrant population', '[01. Screening and Case History] Night sweats', '[01. Screening and Case History] No symptoms related with TB', '[01. Screening and Case History] Number of previous TB episodes', '[01. Screening and Case History] Other symptoms related with TB', '[01. Screening and Case History] Previous TB History', '[01. Screening and Case History] Previous TB regimen', '[01. Screening and Case History] Referral activity', '[01. Screening and Case History] Referral organization', '[01. Screening and Case History] TB CS - HIV infection', '[01. Screening and Case History] TB CS - HIV status date', '[01. Screening and Case History] TB CS - Registration - Type of patient in last TB Treatment', '[01. Screening and Case History] TB CS - Risk factor alcohol', '[01. Screening and Case History] TB CS - Risk factor diabetes', '[01. Screening and Case History] TB CS - Risk factor smoking', '[01. Screening and Case History] TB CS - Risk factor undernourishment', '[01. Screening and Case History] Type of CXR', '[01. Screening and Case History] Weight (in kgs)', '[01. Screening and Case History] Weight loss', '[01. Screening and Case History] Year of last TB Treatment', '[02. Examination Request and Results] Date of Sample Received at Laboratory', '[02. Examination Request and Results] Date of specimen collected', '[02. Examination Request and Results] Name of laboratory examination facility', '[02. Examination Request and Results] Reason for Xpert MTB/XDR request', '[02. Examination Request and Results] Reject sample', '[02. Examination Request and Results] Result data available for dispatch', '[02. Examination Request and Results] Result date', '[02. Examination Request and Results] Result dispatch date', '[02. Examination Request and Results] Samples received (number)', '[02. Examination Request and Results] Specimen type', '[02. Examination Request and Results] TB CS - Resistance classification', '[02. Examination Request and Results] TB-LAB - Sample ID', '[02. Examination Request and Results] TB-LAB - Xpert MTB/RIF Ultra', '[02. Examination Request and Results] TB-LAB - Xpert MTB/RIF Ultra result', '[02. Examination Request and Results] Visual appearance', '[02. Examination Request and Results] Xpert MTB/XDR', '[02. Examination Request and Results] Xpert MTB/XDR (Examination)', '[02. Examination Request and Results] Xpert MTB/XDR Result for Am', '[02. Examination Request and Results] Xpert MTB/XDR Result for Cm', '[02. Examination Request and Results] Xpert MTB/XDR Result for Eto', '[02. Examination Request and Results] Xpert MTB/XDR Result for Fq', '[02. Examination Request and Results] Xpert MTB/XDR Result for INH', '[02. Examination Request and Results] Xpert MTB/XDR Result for Km', '[03. TB Diagnosis] Enroll to TB Case Surveillance Program', '[03. TB Diagnosis] TB CS - Confirmation method', '[03. TB Diagnosis] TB CS - Diagnosis date', '[03. TB Diagnosis] TB CS - Diagnostic note', '[03. TB Diagnosis] TB CS - Manually assigned resistance classification', '[03. TB Diagnosis] TB CS - Reassign resistance classification', '[03. TB Diagnosis] TB CS - Resistance classification', '[03. TB Diagnosis] TB CS - Site of disease', '[03. TB Diagnosis] TB CS Diagnosis', '[03. TB Diagnosis] Type of TB patient', '[1. Screening, Diagnosis and Notification] Age (at screening)', '[1. Screening, Diagnosis and Notification] Any TB drug resistance history?', '[1. Screening, Diagnosis and Notification] BMI', '[1. Screening, Diagnosis and Notification] Breathlessness', '[1. Screening, Diagnosis and Notification] CXR result', '[1. Screening, Diagnosis and Notification] CXR result category', '[1. Screening, Diagnosis and Notification] CXR screening date', '[1. Screening, Diagnosis and Notification] CXR screening done', '[1. Screening, Diagnosis and Notification] CXR screening facility type', '[1. Screening, Diagnosis and Notification] Cough more than 2 weeks', '[1. Screening, Diagnosis and Notification] Current activity', '[1. Screening, Diagnosis and Notification] Fatigue and Tiredness', '[1. Screening, Diagnosis and Notification] Fever more than 2 weeks', '[1. Screening, Diagnosis and Notification] Haemoptysis', '[1. Screening, Diagnosis and Notification] Healthcare worker population', '[1. Screening, Diagnosis and Notification] Height (in inches)', '[1. Screening, Diagnosis and Notification] Loss of appetite', '[1. Screening, Diagnosis and Notification] Migrant population', '[1. Screening, Diagnosis and Notification] Night sweats', '[1. Screening, Diagnosis and Notification] Number of previous TB episodes', '[1. Screening, Diagnosis and Notification] Other symptoms related with TB', '[1. Screening, Diagnosis and Notification] Previous TB History', '[1. Screening, Diagnosis and Notification] Previous TB regimen', '[1. Screening, Diagnosis and Notification] Referral activity', '[1. Screening, Diagnosis and Notification] Referral organization', '[1. Screening, Diagnosis and Notification] Started on Treatment', '[1. Screening, Diagnosis and Notification] TB CS - ART patient ID', '[1. Screening, Diagnosis and Notification] TB CS - Case notification', '[1. Screening, Diagnosis and Notification] TB CS - Confirmation method', '[1. Screening, Diagnosis and Notification] TB CS - Diagnosis date', '[1. Screening, Diagnosis and Notification] TB CS - Diagnostic note', '[1. Screening, Diagnosis and Notification] TB CS - HIV infection', '[1. Screening, Diagnosis and Notification] TB CS - HIV status date', '[1. Screening, Diagnosis and Notification] TB CS - Manually assigned resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Notification date', '[1. Screening, Diagnosis and Notification] TB CS - Reassign resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Registration - Type of patient in last TB Treatment', '[1. Screening, Diagnosis and Notification] TB CS - Resistance classification', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor alcohol', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor diabetes', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor smoking', '[1. Screening, Diagnosis and Notification] TB CS - Risk factor undernourishment', '[1. Screening, Diagnosis and Notification] TB CS - Site of disease', '[1. Screening, Diagnosis and Notification] Type of CXR', '[1. Screening, Diagnosis and Notification] Type of TB patient', '[1. Screening, Diagnosis and Notification] Weight (in kgs)', '[1. Screening, Diagnosis and Notification] Weight loss', '[1. Screening, Diagnosis and Notification] Year of last TB Treatment', '[2. TB Treatment] TB CS - Diagnosis date', '[2. TB Treatment] TB CS - First-line treatment regimen composition', '[2. TB Treatment] TB CS - First-line treatment start date', '[2. TB Treatment] TB CS - Manually assigned resistance classification', '[2. TB Treatment] TB CS - Outcome due date', '[2. TB Treatment] TB CS - Reassign resistance classification', '[2. TB Treatment] TB CS - Resistance at diagnosis', '[2. TB Treatment] TB CS - Resistance classification', '[2. TB Treatment] TB CS - Treatment initiation delay (days)', '[2. TB Treatment] TB CS - Treatment regimen', '[4. Outcome] TB CS - Treatment outcome', '[4. Outcome] TB CS - Treatment outcome delay (weeks)', '[Screening & Testing] BMI', '[Screening & Testing] CXR result category', '[Screening & Testing] CXR screening date', '[Screening & Testing] CXR screening done', '[Screening & Testing] Enroll to Diagnostic Evaluation', '[Screening & Testing] Height (in inches)', '[Screening & Testing] Previous TB History', '[Screening & Testing] Referral activity', '[Screening & Testing] Referral organization', '[Screening & Testing] TB CS - HIV infection', '[Screening & Testing] TB CS - Risk factor alcohol', '[Screening & Testing] TB CS - Risk factor diabetes', '[Screening & Testing] TB CS - Risk factor smoking', '[Screening & Testing] TB CS - Risk factor undernourishment', '[Screening & Testing] TB-HH - Active TB test result', '[Screening & Testing] TB-HH - Active TB testing', '[Screening & Testing] TB-HH - Screening', '[Screening & Testing] Weight (in kgs)', '[TB Screening] Age (at screening)', '[TB Screening] Any TB drug resistance history?', '[TB Screening] BMI', '[TB Screening] Breathlessness', '[TB Screening] CXR result', '[TB Screening] CXR result category', '[TB Screening] CXR screening date', '[TB Screening] CXR screening done', '[TB Screening] CXR screening facility type', '[TB Screening] Chest pain', '[TB Screening] Cough more than 2 weeks', '[TB Screening] Current activity', '[TB Screening] Enroll to Diagnostic Evaluation', '[TB Screening] Fatigue and Tiredness', '[TB Screening] Fever more than 2 weeks', '[TB Screening] Haemoptysis', '[TB Screening] Healthcare worker population', '[TB Screening] Height (in inches)', '[TB Screening] Household Contact', '[TB Screening] Loss of appetite', '[TB Screening] Migrant population', '[TB Screening] Night sweats', '[TB Screening] No symptoms related with TB', '[TB Screening] Number of previous TB episodes', '[TB Screening] Other referral organisation (Specify)', '[TB Screening] Other symptoms related with TB', '[TB Screening] Previous TB History', '[TB Screening] Previous TB regimen', '[TB Screening] Referral activity', '[TB Screening] Referral organization', '[TB Screening] Specify other symptoms', '[TB Screening] TB CS - HIV infection', '[TB Screening] TB CS - HIV status date', '[TB Screening] TB CS - Registration - Type of patient in last TB Treatment', '[TB Screening] TB CS - Risk factor alcohol', '[TB Screening] TB CS - Risk factor diabetes', '[TB Screening] TB CS - Risk factor smoking', '[TB Screening] TB CS - Risk factor undernourishment', '[TB Screening] Type of CXR', '[TB Screening] Weight (in kgs)', '[TB Screening] Weight loss', '[TB Screening] Year of last TB Treatment', 'created', 'enrollment_date', 'enrollment_status', 'lastUpdated', 'orgUnit_id', 'program_id', 'program_name', 'trackedEntityInstance']

In [ ]:
from itertools import product
import io
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
import pandas as pd
import requests
from requests.adapters import HTTPAdapter
import streamlit as st
from urllib3.util import Retry

# --- Backend DHIS2 Processing Functions ---
def build_dhis2_metadata_map(session: requests.Session, base_url: str) -> dict[str, str]:
    meta_map = {}
    endpoints = {
        "trackedEntityAttributes": f"{base_url}/api/trackedEntityAttributes.json?fields=id,displayName&paging=false",
        "dataElements": f"{base_url}/api/dataElements.json?fields=id,displayName&paging=false",
        "programStages": f"{base_url}/api/programStages.json?fields=id,displayName&paging=false",
        "programs": f"{base_url}/api/programs.json?fields=id,displayName&paging=false",
        "organisationUnits": f"{base_url}/api/organisationUnits.json?fields=id,displayName&paging=false",
    }
    for resource, url in endpoints.items():
        try:
            res = session.get(url, timeout=30)
            if res.ok:
                items = res.json().get(resource, [])
                for item in items:
                    meta_map[item["id"]] = item.get("displayName", item["id"])
        except Exception:
            pass
    return meta_map

def get_data_dhis2(web: str, username: str, password: str, idprogram: list[str], idou: list[str]) -> pd.DataFrame:
    base_url = web.rsplit("/api/", 1)[0].rstrip("/")
    endpoint = f"{base_url}/api/trackedEntityInstances.json"

    session = requests.Session()
    session.auth = (username, password)
    session.headers.update({"Accept": "application/json", "User-Agent": "DHIS2-Python-Script/1.0"})

    retries = Retry(total=5, backoff_factor=2, status_forcelist=[500, 502, 503, 504])
    adapter = HTTPAdapter(max_retries=retries)
    session.mount("https://", adapter)
    session.mount("http://", adapter)

    meta_map = build_dhis2_metadata_map(session, base_url)
    all_records = []

    for prog, ou in product(idprogram, idou):
        page = 1
        page_size = 100

        while True:
            params = {
                "program": prog,
                "ou": ou,
                "ouMode": "DESCENDANTS",
                "pageSize": page_size,
                "page": page,
                "totalPages": "true",
                "fields": "trackedEntityInstance,orgUnit,created,lastUpdated,attributes[attribute,displayName,value],enrollments[enrollment,program,orgUnit,enrolledAt,occurredAt,status,events[event,programStage,occurredAt,status,dataValues[dataElement,value]]]",
            }
            try:
                response = session.get(endpoint, params=params, timeout=45)
                if not response.ok:
                    break

                data = response.json()
                instances = data.get("trackedEntityInstances", [])
                if not instances:
                    break

                for instance in instances:
                    ou_id = instance.get("orgUnit")
                    ou_name = meta_map.get(ou_id, ou_id)
                    prog_name = meta_map.get(prog, prog)

                    row = {
                        "program_id": prog,
                        "program_name": prog_name,
                        "trackedEntityInstance": instance.get("trackedEntityInstance"),
                        "orgUnit_id": ou_id,
                        "Org Unit Name": ou_name,
                        "created": instance.get("created"),
                        "lastUpdated": instance.get("lastUpdated"),
                    }

                    for attr in instance.get("attributes", []):
                        attr_id = attr.get("attribute")
                        col_name = attr.get("displayName") or meta_map.get(attr_id) or attr_id
                        row[col_name] = attr.get("value")

                    for enrollment in instance.get("enrollments", []):
                        if enrollment.get("program") == prog:
                            row["enrollment_date"] = enrollment.get("enrolledAt")
                            row["enrollment_status"] = enrollment.get("status")

                            for event in enrollment.get("events", []):
                                stage_id = event.get("programStage")
                                stage_name = meta_map.get(stage_id, f"Stage_{stage_id}")

                                for dv in event.get("dataValues", []):
                                    de_id = dv.get("dataElement")
                                    de_name = meta_map.get(de_id, f"Element_{de_id}")
                                    col_key = f"[{stage_name}] {de_name}"
                                    row[col_key] = dv.get("value")

                    all_records.append(row)

                pager = data.get("pager", {})
                if page >= pager.get("pageCount", 1):
                    break
                page += 1
            except Exception:
                break

    session.close()
    return pd.DataFrame(all_records)

def convert_df_to_excel_bytes(df: pd.DataFrame) -> bytes:
    output = io.BytesIO()
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    header_fill = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
    header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
    data_font = Font(name="Segoe UI", size=10)
    alt_fill = PatternFill(start_color="F2F5F9", end_color="F2F5F9", fill_type="solid")
    thin_border = Border(left=Side(style="thin", color="D9D9D9"), right=Side(style="thin", color="D9D9D9"), top=Side(style="thin", color="D9D9D9"), bottom=Side(style="thin", color="D9D9D9"))

    group_col = "program_name" if "program_name" in df.columns else "program_id"
    for prog_label, prog_df in df.groupby(group_col, dropna=False):
        sheet_title = str(prog_label)[:30] if pd.notna(prog_label) else "Unknown_Program"
        ws = wb.create_sheet(title=sheet_title)
        ws.views.sheetView[0].showGridLines = True

        prog_df_clean = prog_df.dropna(how="all", axis=1)
        headers = list(prog_df_clean.columns)
        ws.append(headers)

        for col_idx in range(1, len(headers) + 1):
            cell = ws.cell(row=1, column=col_idx)
            cell.fill, cell.font = header_fill, header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

        for row_idx, record in enumerate(prog_df_clean.to_dict(orient="records"), start=2):
            ws.append([record.get(col, "") for col in headers])
            is_even = row_idx % 2 == 0
            for col_idx in range(1, len(headers) + 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                cell.font, cell.border = data_font, thin_border
                cell.alignment = Alignment(vertical="center")
                if is_even: cell.fill = alt_fill

        ws.freeze_panes = "A2"
        for col in ws.columns:
            max_len = max(len(str(cell.value or "")) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = min(max(max_len + 4, 12), 45)

    wb.save(output)
    return output.getvalue()

# PROGRAM ID { Registration&Screening : UZF0HrTlps0 , 
#               DiagnosticEvaluation : GvywHD6crky , 
#               TBCaseSurveillence : Lt6P15ps7f6 ,
#               TBContactInvestigationTPT : cQsXTtAJ3HW }

# ORGANISATION UNIT ID { YTPMATA_HLG : KqjORlUe8Yc , 
#                       YTPMATA_KMD : rTTCKrLpxTB ,
#                       YTPMATA_SDG : XHz6CPxTAbR , 
#                       YTPMMA_TGG : MlBn9fEP74R ,
#                       YTPMATA_TGG : aBfPB9AwbF5 ,
#                       YTPMATA_SOK : OeZsFpNKLP5 ,
#                       YTPMATA_MYG : mPwLv1cjror ,
#                       YTPMATA_SPT : aMAEOgli6W8 }

# # --- Streamlit UI Components ---
# st.title("📊 DHIS2 Tracker Exporter")
# st.markdown("Extract tracked entity instances from DHIS2 and download formatted Excel files.")

# with st.form("dhis2_form"):
#     web_url = st.text_input("DHIS2 Base URL", value="https://hmistraining.mm.dhis2.net/train")
#     col1, col2 = st.columns(2)
#     with col1:
#         username = st.text_input("Username", value="Ygn_NTP1")
#     with col2:
#         password = st.text_input("Password", type="password", value="District@1")



#     prog_input = st.text_area("Program IDs (comma-separated)", value="UZF0HrTlps0, GvywHD6crky, Lt6P15ps7f6, cQsXTtAJ3HW")




#     ou_input = st.text_area("Org Unit IDs (comma-separated)", value="KqjORlUe8Yc, rTTCKrLpxTB, XHz6CPxTAbR, MlBn9fEP74R, aBfPB9AwbF5, OeZsFpNKLP5, mPwLv1cjror, aMAEOgli6W8")
    
#     submitted = st.form_submit_button("Extract & Process Data")

# if submitted:
#     prog_ids = [p.strip() for p in prog_input.split(",") if p.strip()]
#     ou_ids = [o.strip() for o in ou_input.split(",") if o.strip()]

#     with st.spinner("Connecting to DHIS2 and extracting data..."):
#         df_result = get_data_dhis2(web_url, username, password, prog_ids, ou_ids)

#     if df_result.empty:
#         st.error("No data extracted. Check your parameters or credentials.")
#     else:
#         st.success(f"Successfully extracted {len(df_result)} records!")
#         excel_data = convert_df_to_excel_bytes(df_result)
        
#         st.download_button(
#             label="💾 Download Excel File (.xlsx)",
#             data=excel_data,
#             file_name="DHIS2_Tracker_Export.xlsx",
#             mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
#             type="primary"
#         )


# --- Streamlit UI Components ---
st.title("📊 DHIS2 Tracker Exporter")
st.markdown("Extract tracked entity instances from DHIS2 and download formatted Excel files.")

# Define Mappings
PROGRAM_MAP = {
    "Registration & Screening": "UZF0HrTlps0",
    "Diagnostic Evaluation": "GvywHD6crky",
    "TB Case Surveillance": "Lt6P15ps7f6",
    "TB Contact Investigation TPT": "cQsXTtAJ3HW"
}

TOWNSHIP_OU_MAP = {
    "HLG (Hlaing)": ["KqjORlUe8Yc"],
    "KMD (Kyeemyindaing)": ["rTTCKrLpxTB"],
    "SDG (Dagon Myothit South)": ["XHz6CPxTAbR"],
    "TGG (Thingangyun)": ["aBfPB9AwbF5"],
    "SOK (South Okkalapa)": ["OeZsFpNKLP5"],
    "MYG (Mayangone)": ["mPwLv1cjror"],
    "SPT (Shwepyithar)": ["aMAEOgli6W8"]
}

with st.form("dhis2_form"):
    web_url = st.text_input("DHIS2 Base URL", value="https://hmistraining.mm.dhis2.net/train")
    col1, col2 = st.columns(2)
    with col1:
        username = st.text_input("Username", value="Ygn_NTP1")
    with col2:
        password = st.text_input("Password", type="password", value="District@1")

    # Program Selection UI
    selected_programs = st.multiselect(
        "Select Programs",
        options=list(PROGRAM_MAP.keys()),
        default=list(PROGRAM_MAP.keys())
    )

    # Township Selection UI
    selected_townships = st.multiselect(
        "Select Townships",
        options=list(TOWNSHIP_OU_MAP.keys()),
        default=list(TOWNSHIP_OU_MAP.keys())
    )

    submitted = st.form_submit_button("Extract & Process Data")

if submitted:
    # Extract selected Program IDs
    prog_ids = [PROGRAM_MAP[p] for p in selected_programs]

    # Extract and flatten selected Township Org Unit IDs
    ou_ids = []
    for township in selected_townships:
        ou_ids.extend(TOWNSHIP_OU_MAP[township])

    if not prog_ids or not ou_ids:
        st.warning("Please select at least one Program and one Township.")
    else:
        with st.spinner("Connecting to DHIS2 and extracting data..."):
            df_result = get_data_dhis2(web_url, username, password, prog_ids, ou_ids)

        if df_result.empty:
            st.error("No data extracted. Check your parameters or credentials.")
        else:
            st.success(f"Successfully extracted {len(df_result)} records!")
            excel_data = convert_df_to_excel_bytes(df_result)
            
            st.download_button(
                label="💾 Download Excel File (.xlsx)",
                data=excel_data,
                file_name="DHIS2_Tracker_Export.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                type="primary"
            )